package com.example.platform.render.domain.render.local;

/**
 * Origin of a local media source.
 *
 * <p>Only platform-generated or controlled test fixture origins are accepted.
 * User-provided, remote, and storage-referenced origins are rejected.</p>
 */
public enum LocalMediaSourceOrigin {

    /**
     * Generated by platform-owned code (e.g., FFmpeg testsrc/colorsource).
     */
    PLATFORM_GENERATED,

    /**
     * Controlled test fixture committed or generated for testing.
     */
    CONTROLLED_TEST_FIXTURE
}
