package com.example.platform.render.domain.render.local;

/**
 * Diagnostic codes for issues encountered during local render smoke
 * and BasicRenderPlan-to-local-runner bridge execution.
 */
public enum LocalRenderSmokeIssueCode {
    // P2L.0 local smoke codes
    FFMPEG_NOT_AVAILABLE,
    FFPROBE_NOT_AVAILABLE,
    OUTPUT_DIRECTORY_UNAVAILABLE,
    OUTPUT_FILE_MISSING,
    FFMPEG_EXIT_NONZERO,
    FFPROBE_EXIT_NONZERO,
    PROCESS_TIMEOUT,
    INVALID_OUTPUT_DURATION,
    INVALID_OUTPUT_WIDTH,
    INVALID_OUTPUT_HEIGHT,
    INVALID_OUTPUT_CODEC,
    INVALID_OUTPUT_FORMAT,
    COMMAND_ALLOWLIST_VIOLATION,
    SHELL_INVOCATION_FORBIDDEN,
    USER_COMMAND_FORBIDDEN,
    RAW_FILTERGRAPH_INPUT_FORBIDDEN,
    OPEN_CUE_FORBIDDEN,
    PRODUCT_RUNTIME_FORBIDDEN,
    STORAGE_RUNTIME_FORBIDDEN,
    RENDER_JOB_CREATION_FORBIDDEN,
    PRODUCT_CREATION_FORBIDDEN,
    ARTIFACT_DAG_FORBIDDEN,
    REMOTION_EXECUTION_FORBIDDEN,
    PUBLIC_API_FORBIDDEN,

    // P2L.1 BasicRenderPlan bridge codes
    BASIC_RENDER_PLAN_MISSING,
    BASIC_RENDER_PLAN_INVALID,
    BASIC_RENDER_PLAN_BLOCKED,
    BASIC_RENDER_PLAN_UNSUPPORTED,
    UNSUPPORTED_RENDER_STAGE,
    UNSUPPORTED_RENDER_STEP,
    OUTPUT_PROFILE_MISSING,
    OUTPUT_PROFILE_UNSUPPORTED,
    SYNTHETIC_INPUT_REQUIRED,

    // P2L.2 caption overlay codes
    CAPTION_OVERLAY_MISSING,
    CAPTION_OVERLAY_UNSUPPORTED,
    CAPTION_TEXT_MISSING,
    CAPTION_TEXT_TOO_LONG,
    CAPTION_TIME_RANGE_INVALID,
    CAPTION_PLACEMENT_UNSUPPORTED,
    CAPTION_STYLE_UNSUPPORTED,
    CAPTION_FONT_UNSUPPORTED,
    CAPTION_RAW_FILTERGRAPH_FORBIDDEN,
    CAPTION_RAW_ASS_STYLE_FORBIDDEN,
    CAPTION_EXTERNAL_SUBTITLE_FORBIDDEN,
    CAPTION_FONT_PATH_FORBIDDEN,
    CAPTION_OVERLAY_RENDER_FAILED
}
