package com.example.platform.render.domain.render.local;

/**
 * Diagnostic codes for issues encountered during local render smoke.
 */
public enum LocalRenderSmokeIssueCode {
    FFMPEG_NOT_AVAILABLE,
    FFPROBE_NOT_AVAILABLE,
    OUTPUT_DIRECTORY_UNAVAILABLE,
    OUTPUT_FILE_MISSING,
    FFMPEG_EXIT_NONZERO,
    FFPROBE_EXIT_NONZERO,
    PROCESS_TIMEOUT,
    INVALID_OUTPUT_DURATION,
    INVALID_OUTPUT_WIDTH,
    INVALID_OUTPUT_HEIGHT,
    INVALID_OUTPUT_CODEC,
    INVALID_OUTPUT_FORMAT,
    COMMAND_ALLOWLIST_VIOLATION,
    SHELL_INVOCATION_FORBIDDEN,
    USER_COMMAND_FORBIDDEN,
    RAW_FILTERGRAPH_INPUT_FORBIDDEN,
    OPEN_CUE_FORBIDDEN,
    PRODUCT_RUNTIME_FORBIDDEN,
    STORAGE_RUNTIME_FORBIDDEN,
    RENDER_JOB_CREATION_FORBIDDEN,
    PRODUCT_CREATION_FORBIDDEN,
    ARTIFACT_DAG_FORBIDDEN,
    REMOTION_EXECUTION_FORBIDDEN,
    PUBLIC_API_FORBIDDEN
}
