package com.example.platform.timeline.revisioncommand;

/**
 * REVISION_COMMAND_MODEL_V1 (RC48/§54): typed Revision Command errors —
 * independent of OperationErrorCode authority.
 */
public enum RevisionCommandErrorCode {
    REVISION_NOT_FOUND,
    SOURCE_REVISION_NOT_FOUND,
    TARGET_REVISION_NOT_FOUND,
    REF_NOT_FOUND,
    REF_ALREADY_EXISTS,
    INVALID_REF,
    CROSS_PROJECT_REVISION,
    STALE_TARGET_REF,
    NO_COMMON_ANCESTOR,
    AMBIGUOUS_MERGE_BASE,
    MERGE_CONFLICT,
    INVALID_PARENT_SET,
    UNSUPPORTED_HISTORY_FORMAT,
    DETACHED_WRITE_FORBIDDEN,
    PROTECTED_REF,
    AUTHORIZATION_DENIED,
    AUTHORIZATION_CONTEXT_MISMATCH,
    IDEMPOTENCY_KEY_CONFLICT,
    REVISION_COMMAND_PLAN_CHANGED,
    PERSISTENCE_FAILURE,
    REVISION_GRAPH_FAILURE
}
