apiVersion: v1
kind: Service
metadata:
  name: egress-proxy
  namespace: media-platform-production
  labels:
    app: egress-proxy
    component: network-egress
spec:
  type: ClusterIP
  selector:
    app: egress-proxy
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
