package com.example.platform.timeline.canonicalmodel;

public enum TimelineDiagnosticCode {
    TIMELINE_ROOT_NULL,
    TIMELINE_ID_MISSING,
    TIMELINE_TRACK_ID_MISSING,
    TIMELINE_TRACK_ID_DUPLICATE,
    TIMELINE_TRACK_TYPE_UNSUPPORTED,
    TIMELINE_CLIP_ID_MISSING,
    TIMELINE_CLIP_ID_DUPLICATE,
    TIMELINE_SOURCE_REF_MISSING,
    TIMELINE_TIME_NEGATIVE,
    TIMELINE_TIME_OVERFLOW,
    TIMELINE_DURATION_ZERO,
    TIMELINE_DURATION_NEGATIVE,
    TIMELINE_SOURCE_RANGE_INVALID,
    TIMELINE_CLIP_OVERLAP,
    TIMELINE_ORDERING_INVALID,
    TIMELINE_Z_ORDER_INVALID,
    TIMELINE_AUDIO_GAIN_INVALID,
    TIMELINE_CONSTRUCT_UNSUPPORTED,
    TIMELINE_TRANSITION_ENDPOINT_MISSING,
    TIMELINE_TRANSITION_SELF_REFERENCE,
    TIMELINE_AUTOMATION_TARGET_MISSING
}
