package com.example.platform.sandbox;

@org.springframework.modulith.NamedInterface("API")
public enum SandboxFailureCode {
    SANDBOX_UNAVAILABLE,
    SANDBOX_CAPABILITY_UNSUPPORTED,
    SANDBOX_POLICY_UNSATISFIABLE,
    SANDBOX_SETUP_FAILED,
    PROCESS_LAUNCH_FAILED,
    PROCESS_TERMINATED_BY_LIMIT,
    PROCESS_TIMEOUT,
    PROCESS_CRASHED,
    FILESYSTEM_POLICY_VIOLATION,
    NETWORK_POLICY_VIOLATION,
    SECRET_INJECTION_FAILED,
    PRIVILEGE_SETUP_FAILED,
    DEVICE_EXPOSURE_FAILED,
    OUTPUT_STAGING_FAILED,
    SANDBOX_CLEANUP_FAILED,
    SANDBOX_RUNTIME_LOST
}
