package com.example.platform.product.domain;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * AI suggestion for timeline or render optimization.
 * Generated by analyzing TimelineGraph, ArtifactGraph, and TraceGraph.
 */
public record AiSuggestion(
        String id,
        String projectId,
        String workspaceId,
        SuggestionType type,
        String title,
        String description,
        double confidence,
        List<String> affectedClipIds,
        Map<String, Object> suggestedChanges,
        String traceId,
        Instant createdAt
) {
    /**
     * Create a timeline layout suggestion.
     */
    public static AiSuggestion timelineLayout(String id, String projectId, String workspaceId,
                                               String title, String description,
                                               double confidence, List<String> affectedClipIds,
                                               Map<String, Object> changes, String traceId) {
        return new AiSuggestion(id, projectId, workspaceId, SuggestionType.TIMELINE_LAYOUT,
                title, description, confidence, affectedClipIds, changes, traceId, Instant.now());
    }

    /**
     * Create an effect suggestion.
     */
    public static AiSuggestion effect(String id, String projectId, String workspaceId,
                                       String title, String description,
                                       double confidence, List<String> affectedClipIds,
                                       Map<String, Object> changes, String traceId) {
        return new AiSuggestion(id, projectId, workspaceId, SuggestionType.EFFECT,
                title, description, confidence, affectedClipIds, changes, traceId, Instant.now());
    }

    /**
     * Create a trim optimization suggestion.
     */
    public static AiSuggestion trimOptimization(String id, String projectId, String workspaceId,
                                                  String title, String description,
                                                  double confidence, List<String> affectedClipIds,
                                                  Map<String, Object> changes, String traceId) {
        return new AiSuggestion(id, projectId, workspaceId, SuggestionType.TRIM_OPTIMIZATION,
                title, description, confidence, affectedClipIds, changes, traceId, Instant.now());
    }

    /**
     * Create a render preset suggestion.
     */
    public static AiSuggestion renderPreset(String id, String projectId, String workspaceId,
                                             String title, String description,
                                             double confidence, Map<String, Object> changes,
                                             String traceId) {
        return new AiSuggestion(id, projectId, workspaceId, SuggestionType.RENDER_PRESET,
                title, description, confidence, List.of(), changes, traceId, Instant.now());
    }

    /**
     * Check if suggestion is high confidence.
     */
    public boolean isHighConfidence() {
        return confidence >= 0.8;
    }

    /**
     * Check if suggestion affects specific clips.
     */
    public boolean affectsClips() {
        return !affectedClipIds.isEmpty();
    }
}
