package com.example.platform.execution.compatibility;

/** Typed, deterministic Stage-1 incompatibility algebra. */
public enum StaticCompatibilityFailure {
    CAPABILITY_UNSUPPORTED,
    CONTRACT_VERSION_UNSUPPORTED,
    ARTIFACT_INCOMPATIBLE,
    CODEC_UNSUPPORTED,
    DEVICE_KIND_UNSUPPORTED_IN_PRINCIPLE,
    PROVIDER_RUNTIME_CLASS_UNSUPPORTED,
    PROVIDER_CONTRACT_INCOMPATIBLE,
    SANDBOX_MODE_UNSUPPORTED,
    DETERMINISM_UNSUPPORTED,
    CROSS_PROVIDER_BOUNDARY_INCOMPATIBLE,
    LOWERING_SEMANTICALLY_UNREPRESENTABLE,
    UNKNOWN_STATIC_COMPATIBILITY
}
