package com.example.platform.render.domain.asset;

/**
 * Asset governance metadata fields.
 *
 * <p>Expresses classification, license, retention, and AI provenance flags.
 * Does not call the policy-governance-module.</p>
 *
 * @param classification public / internal / confidential / restricted
 * @param license        license type
 * @param retentionPolicy retention duration or policy key
 * @param securityLevel  L1 / L2 / L3 / L4
 * @param containsPii    whether this asset contains personally identifiable information
 * @param aiGenerated    whether this asset was generated by AI
 */
public record AssetGovernanceMetadata(
        String classification,
        String license,
        String retentionPolicy,
        String securityLevel,
        boolean containsPii,
        boolean aiGenerated) {

    public static AssetGovernanceMetadata defaults() {
        return new AssetGovernanceMetadata(null, null, null, null, false, false);
    }
}
