package com.example.platform.render.domain.plan;

/**
 * OPERATION_PLAN_TRANSACTION_MODEL_V1 (PT31/§43): typed planning/apply errors.
 * Extends the typed error vocabulary; never exception strings as stable API.
 */
public enum PlanErrorCode {
    INVALID_PLAN,
    STALE_BASE_REVISION,
    STALE_TARGET_REF,
    PLAN_CHANGED,
    AUTHORIZATION_DENIED,
    AUTHORIZATION_CONTEXT_MISMATCH,
    AUTHORIZATION_STALE,
    IDEMPOTENCY_KEY_CONFLICT,
    TARGET_MISSING,
    UNSUPPORTED_TEMPORAL_STATE,
    UNSUPPORTED_AUDIO_TEMPORAL_BEHAVIOR,
    SYNC_ANCHOR_INVALIDATED,
    GROUP_CARDINALITY_CONFLICT,
    PLACEMENT_CONFLICT,
    BATCH_CONFLICT,
    CANONICAL_INVARIANT_VIOLATION,
    PERSISTENCE_FAILURE,
    REF_UPDATE_FAILURE,
    APPLY_UNKNOWN_FAILURE
}
