package com.example.platform.render.domain.timeline.internal;

/**
 * Semantic diff change classification for render impact analysis.
 */
public enum SemanticChangeType {
    PROJECT_TIMEBASE_CHANGED,
    PROJECT_RESOLUTION_CHANGED,
    PROJECT_COLOR_CHANGED,
    ASSET_URI_CHANGED,
    ASSET_PROBE_CHANGED,
    CLIP_ADDED,
    CLIP_REMOVED,
    CLIP_RANGE_CHANGED,
    CLIP_SPEED_CHANGED,
    CLIP_EFFECT_CHANGED,
    LAYER_ADDED,
    LAYER_REMOVED,
    LAYER_CONTENT_CHANGED,
    LAYER_TRANSFORM_CHANGED,
    SUBTITLE_CUE_CHANGED,
    SUBTITLE_STYLE_CHANGED,
    AUDIO_BUS_CHANGED,
    AUDIO_STEM_CHANGED,
    EXTERNAL_NODE_CHANGED,
    TRANSITION_CHANGED,
    OUTPUT_PROFILE_CHANGED,
    PACKAGING_PARAM_CHANGED,
    FINAL_COMPOSER_CHANGED,
    REVISION_ONLY,
    UNKNOWN
}
