package com.example.platform.composition.app;

import com.example.platform.composition.domain.CompositionModels.*;
import org.springframework.stereotype.Service;
import java.util.*;
import com.example.platform.composition.app.CompositionRepository.Kind;

@Service
public class CompositionService {
    private final ProviderRegistryBoundary registry;
    private final CompositionRepository repository;
    private final CompositionAccess access;
    private final CompositionResourceAuthority resources;
    public CompositionService(ProviderRegistryBoundary registry, CompositionRepository repository, CompositionAccess access, CompositionResourceAuthority resources) { this.registry=registry; this.repository=repository; this.access=access; this.resources=resources; }
    public List<CapabilityAvailability> catalog(String workspace) { access.resolve(workspace); return registry.publicAvailability(); }
    public TemplateWorkflow saveWorkflow(TemplateWorkflow value, String ignoredTenant) { var scope=access.resolve(value.workspaceId()); if(value.lifecycle()!=Lifecycle.DRAFT) throw new OptimisticConcurrencyException(); var normalized=new TemplateWorkflow(value.id(),value.version(),value.name(),value.steps(),value.bindings(),value.parameters(),value.requiredCapabilities(),value.executionModes(),value.requiredAssets(),value.outputs(),value.entry(),value.estimate(),value.reliability(),Lifecycle.DRAFT,scope.tenantId(),scope.workspaceId(),value.revision()); var saved=workflowCopy(normalized,Lifecycle.DRAFT,value.revision()+1); repository.save(Kind.WORKFLOW,scope.tenantId(),scope.workspaceId(),value.id(),value.version(),value.revision(),saved); return saved; }
    public Application saveApplication(Application value,String ignoredTenant) { var scope=access.resolve(value.workspaceId()); if(value.lifecycle()!=Lifecycle.DRAFT) throw new OptimisticConcurrencyException(); var normalized=new Application(value.id(),value.version(),value.displayName(),value.description(),value.input(),value.output(),value.requiredCapabilities(),value.workflowIds(),value.requiredAssets(),value.entitlements(),value.executionModes(),Lifecycle.DRAFT,scope.tenantId(),scope.workspaceId(),value.revision()); var saved=applicationCopy(normalized,Lifecycle.DRAFT,value.revision()+1); repository.save(Kind.APPLICATION,scope.tenantId(),scope.workspaceId(),value.id(),value.version(),value.revision(),saved); return saved; }
    public Optional<TemplateWorkflow> workflow(String tenant,String workspace,String id){return repository.draft(Kind.WORKFLOW,tenant,workspace,id,TemplateWorkflow.class);}
    public Optional<Application> application(String tenant,String workspace,String id){return repository.draft(Kind.APPLICATION,tenant,workspace,id,Application.class);}
    public Optional<TemplateWorkflow> workflowVersion(String tenant,String workspace,String id,String version){return repository.version(Kind.WORKFLOW,tenant,workspace,id,version,TemplateWorkflow.class);}
    public Optional<Application> applicationVersion(String tenant,String workspace,String id,String version){return repository.version(Kind.APPLICATION,tenant,workspace,id,version,Application.class);}
    public Map<String,Object> compareWorkflowVersions(String tenant,String workspace,String id,String left,String right){var a=workflowVersion(tenant,workspace,id,left).orElseThrow();var b=workflowVersion(tenant,workspace,id,right).orElseThrow();return Map.of("left",left,"right",right,"sameSteps",a.steps().equals(b.steps()),"sameParameters",a.parameters().equals(b.parameters()),"sameExecutionModes",a.executionModes().equals(b.executionModes()));}
    public Map<String,Object> compareApplicationVersions(String tenant,String workspace,String id,String left,String right){var a=applicationVersion(tenant,workspace,id,left).orElseThrow();var b=applicationVersion(tenant,workspace,id,right).orElseThrow();return Map.of("left",left,"right",right,"sameWorkflows",a.workflowIds().equals(b.workflowIds()),"sameCapabilities",a.requiredCapabilities().equals(b.requiredCapabilities()),"sameEntitlements",a.entitlements().equals(b.entitlements()));}
    public ValidationResult validateWorkflow(TemplateWorkflow w, String tenant, Set<String> ignored){var scope=access.resolve(w.workspaceId()); var check=resources.resolve(scope.tenantId(),scope.workspaceId(),scope.actorId(),w.id(),w.requiredAssets(),Set.of(),w.estimate().quotaUnits().longValue()); var r=CompositionValidator.validate(w,registry,check.availableAssets(),check.grantedEntitlements()); r=withResourceIssues(r,check.issues()); repository.snapshot(scope.tenantId(),scope.workspaceId(),w.id(),r); return r;}
    public ValidationResult validateApplication(Application a,String tenant,Set<String> ignoredAssets,Set<String> ignoredEntitlements){var scope=access.resolve(a.workspaceId()); List<TemplateWorkflow> ws=a.workflowIds().stream().map(id->workflow(scope.tenantId(),scope.workspaceId(),id)).flatMap(Optional::stream).toList(); Set<String> assets=new HashSet<>(a.requiredAssets()); ws.forEach(w->assets.addAll(w.requiredAssets())); var check=resources.resolve(scope.tenantId(),scope.workspaceId(),scope.actorId(),a.id(),assets,a.entitlements(),ws.stream().mapToLong(w->w.estimate().quotaUnits().longValue()).sum()); var r=CompositionValidator.validateApplication(a,ws,registry,check.availableAssets(),check.grantedEntitlements()); r=withResourceIssues(r,check.issues()); repository.snapshot(scope.tenantId(),scope.workspaceId(),a.id(),r); return r;}
    public TemplateWorkflow publishWorkflow(String tenant,String workspace,String id){var w=workflow(tenant,workspace,id).orElseThrow(); var r=validateWorkflow(w,tenant,Set.of()); if(!r.ready()) throw new ValidationException(r); var p=workflowCopy(w,Lifecycle.PUBLISHED,w.revision()+1); repository.publish(Kind.WORKFLOW,tenant,workspace,id,w.version(),w.revision(),p); return p;}
    public Application publishApplication(String tenant,String workspace,String id,Set<String> assets,Set<String> entitlements){var a=application(tenant,workspace,id).orElseThrow(); var r=validateApplication(a,tenant,assets,entitlements); if(!r.ready()) throw new ValidationException(r); var p=applicationCopy(a,Lifecycle.PUBLISHED,a.revision()+1); repository.publish(Kind.APPLICATION,tenant,workspace,id,a.version(),a.revision(),p); return p;}
    static TemplateWorkflow workflowCopy(TemplateWorkflow w,Lifecycle state,long revision){return new TemplateWorkflow(w.id(),w.version(),w.name(),w.steps(),w.bindings(),w.parameters(),w.requiredCapabilities(),w.executionModes(),w.requiredAssets(),w.outputs(),w.entry(),w.estimate(),w.reliability(),state,w.tenantId(),w.workspaceId(),revision);}
    static Application applicationCopy(Application a,Lifecycle state,long revision){return new Application(a.id(),a.version(),a.displayName(),a.description(),a.input(),a.output(),a.requiredCapabilities(),a.workflowIds(),a.requiredAssets(),a.entitlements(),a.executionModes(),state,a.tenantId(),a.workspaceId(),revision);}
    private static ValidationResult withResourceIssues(ValidationResult result,List<CompositionResourceAuthority.CompositionModelsIssue> resourceIssues){if(resourceIssues.isEmpty())return result; var issues=new ArrayList<>(result.issues()); resourceIssues.forEach(i->issues.add(new ValidationIssue(i.code(),i.path(),i.message(),Severity.ERROR,"application","",i.path()))); return new ValidationResult(false,issues,result.snapshotId());}
    private static void ensureTenant(String value,String current){if(!Objects.equals(value,current)) throw new ScopeViolationException();}
    public static class OptimisticConcurrencyException extends RuntimeException{}
    public static class ScopeViolationException extends RuntimeException{}
    public static class ValidationException extends RuntimeException{public final ValidationResult result; ValidationException(ValidationResult r){result=r;}}
}
