package com.example.platform.composition.app;

import com.example.platform.composition.domain.CompositionModels.*;
import java.util.*;
import java.util.regex.*;

public final class CompositionValidator {
    private CompositionValidator() {}
    private static ValidationIssue issue(String code, String path, String message, String type, String id, String location) { return new ValidationIssue(code, path, message, Severity.ERROR, type, id, location); }
    static ValidationResult validate(TemplateWorkflow workflow, ProviderRegistryBoundary registry, Set<String> availableAssets, Set<String> entitlements) {
        List<ValidationIssue> issues = new ArrayList<>(); Map<String, WorkflowStep> steps = new LinkedHashMap<>(); Map<String,Integer> inputBindings = new HashMap<>();
        for (WorkflowStep step : workflow.steps()) {
            if (steps.put(step.id(), step) != null) issues.add(issue("DUPLICATE_STEP", "steps." + step.id(), "step id is duplicated", "workflow", workflow.id(), "node:" + step.id()));
            var cap = registry.resolve(step.capabilityId(), step.capabilityVersion());
            if (cap.isEmpty()) issues.add(issue("MISSING_CAPABILITY", "steps." + step.id(), "capability is unavailable", "workflow", workflow.id(), "node:" + step.id()));
            else if (cap.get().availability() != Availability.AVAILABLE) issues.add(issue("CAPABILITY_UNAVAILABLE", "steps." + step.id(), cap.get().summary(), "workflow", workflow.id(), "node:" + step.id()));
            else if (Collections.disjoint(cap.get().executionModes(), workflow.executionModes())) issues.add(issue("UNSUPPORTED_EXECUTION_MODE", "steps." + step.id(), "requested execution mode is not supported by the capability", "workflow", workflow.id(), "node:" + step.id()));
        }
        for (String cap : workflow.requiredCapabilities()) if (workflow.steps().stream().noneMatch(s -> s.capabilityId().equals(cap))) issues.add(issue("MISSING_CAPABILITY", "requiredCapabilities", cap, "workflow", workflow.id(), "requiredCapabilities"));
        for (String asset : workflow.requiredAssets()) if (!availableAssets.contains(asset)) issues.add(issue("MISSING_ASSET", "requiredAssets", asset, "workflow", workflow.id(), "requiredAssets"));
        for (int i = 0; i < workflow.bindings().size(); i++) {
            Binding b = workflow.bindings().get(i); String path = "bindings[" + i + "]"; String target = b.toStep() + "/" + b.toInput(); inputBindings.merge(target, 1, Integer::sum);
            if (inputBindings.get(target) > 1) issues.add(issue("CARDINALITY_MISMATCH", path, "input has multiple bindings", "workflow", workflow.id(), "binding:" + i));
            if (!steps.containsKey(b.fromStep()) || !steps.containsKey(b.toStep())) issues.add(issue("INVALID_GRAPH_EDGE", path, "binding references an unknown step", "workflow", workflow.id(), "binding:" + i));
            else { String result = compatible(steps.get(b.fromStep()), steps.get(b.toStep()), b, registry); if (!result.isEmpty()) issues.add(issue(result, path, "binding ports or contracts are incompatible", "workflow", workflow.id(), "binding:" + i)); }
        }
        if (hasCycle(workflow.steps(), workflow.bindings())) issues.add(issue("CIRCULAR_DEPENDENCY", "bindings", "workflow graph contains a cycle", "workflow", workflow.id(), "bindings"));
        Set<String> incoming = new HashSet<>(), outgoing = new HashSet<>(); workflow.bindings().forEach(b -> { incoming.add(b.toStep()); outgoing.add(b.fromStep()); });
        Set<String> roots = new LinkedHashSet<>(); steps.keySet().forEach(id -> { if (!incoming.contains(id)) roots.add(id); }); Set<String> reachable = new HashSet<>(); roots.stream().findFirst().ifPresent(r -> reach(r, workflow.bindings(), reachable));
        steps.keySet().stream().filter(id -> !reachable.contains(id)).forEach(id -> issues.add(issue("UNREACHABLE_NODE", "steps." + id, "step is unreachable from a workflow entry", "workflow", workflow.id(), "node:" + id)));
        if (workflow.steps().isEmpty()) issues.add(issue("EMPTY_WORKFLOW_GRAPH", "steps", "workflow must contain a graph", "workflow", workflow.id(), "steps")); if (workflow.outputs().isEmpty()) issues.add(issue("MISSING_WORKFLOW_OUTPUT", "outputs", "workflow must declare at least one output", "workflow", workflow.id(), "outputs"));
        Set<String> terminalNodes = new HashSet<>(steps.keySet()); terminalNodes.removeAll(outgoing); if (terminalNodes.isEmpty()) issues.add(issue("NO_TERMINAL_OUTPUT", "outputs", "workflow must contain a reachable terminal output step", "workflow", workflow.id(), "outputs"));
        Set<String> declared = new HashSet<>();
        for (int i = 0; i < workflow.outputs().size(); i++) {
            WorkflowOutput output = workflow.outputs().get(i); String path = "outputs[" + i + "]"; declared.add(output.stepId());
            if (!steps.containsKey(output.stepId())) issues.add(issue("INVALID_OUTPUT_NODE", path + ".stepId", "output references an unknown step", "workflow", workflow.id(), "output:" + i));
            else if (!reachable.contains(output.stepId())) issues.add(issue("UNREACHABLE_OUTPUT", path + ".stepId", "output step is unreachable", "workflow", workflow.id(), "output:" + i));
            else if (!terminalNodes.contains(output.stepId())) issues.add(issue("OUTPUT_NOT_TERMINAL", path + ".stepId", "output must reference a terminal node", "workflow", workflow.id(), "output:" + i));
            else { var cap = registry.resolve(steps.get(output.stepId()).capabilityId(), steps.get(output.stepId()).capabilityVersion()); if (cap.isEmpty() || !portMatches(output.port(), cap.get().output().name(), "output") || !output.type().equals(cap.get().output().name())) issues.add(issue("INVALID_OUTPUT_PORT", path, "declared output port or contract does not match the capability", "workflow", workflow.id(), "output:" + i)); }
        }
        terminalNodes.stream().filter(id -> reachable.contains(id) && !declared.contains(id)).forEach(id -> issues.add(issue("UNDECLARED_TERMINAL_OUTPUT", "outputs", "reachable terminal node must be declared as an output: " + id, "workflow", workflow.id(), "node:" + id)));
        if (workflow.executionModes().isEmpty()) issues.add(issue("UNSUPPORTED_EXECUTION_MODE", "executionModes", "at least one execution mode is required", "workflow", workflow.id(), "executionModes"));
        for (int i = 0; i < workflow.parameters().size(); i++) validateParameter(workflow.parameters().get(i), i, workflow.id(), issues);
        return new ValidationResult(issues.stream().noneMatch(i -> i.severity() == Severity.ERROR), issues, UUID.randomUUID().toString());
    }
    static ValidationResult validateApplication(Application app, List<TemplateWorkflow> workflows, ProviderRegistryBoundary registry, Set<String> assets, Set<String> entitlements) {
        List<ValidationIssue> issues = new ArrayList<>(); if (app.workflowIds().isEmpty()) issues.add(issue("MISSING_WORKFLOW", "workflowIds", "application requires a workflow", "application", app.id(), "workflowIds"));
        for (int i = 0; i < app.workflowIds().size(); i++) { final int index = i; String id = app.workflowIds().get(i); workflows.stream().filter(w -> w.id().equals(id)).findFirst().ifPresentOrElse(w -> { var r = validate(w, registry, assets, entitlements); r.issues().forEach(x -> issues.add(new ValidationIssue(x.code(), "workflows[" + index + "]." + x.path(), x.message(), x.severity(), "workflow", w.id(), x.location()))); if (Collections.disjoint(app.executionModes(), w.executionModes())) issues.add(issue("APPLICATION_EXECUTION_MODE_UNSUPPORTED", "executionModes", "application mode is unsupported by workflow " + id, "application", app.id(), "executionModes")); String compatibility = versionCompatibility(app.version(), w.version()); if (!compatibility.equals("OK")) issues.add(issue(compatibility, "workflowIds[" + index + "]", "application and workflow versions are incompatible or malformed", "application", app.id(), "workflow:" + id)); }, () -> issues.add(issue("MISSING_WORKFLOW", "workflowIds[" + index + "]", id, "application", app.id(), "workflow:" + id))); }
        for (String cap : app.requiredCapabilities()) if (registry.publicAvailability().stream().noneMatch(c -> c.capabilityId().equals(cap) && c.availability() == Availability.AVAILABLE)) issues.add(issue("MISSING_CAPABILITY", "requiredCapabilities", cap, "application", app.id(), "requiredCapabilities"));
        for (String a : app.requiredAssets()) if (!assets.contains(a)) issues.add(issue("MISSING_ASSET", "requiredAssets", a, "application", app.id(), "requiredAssets")); for (String e : app.entitlements()) if (!entitlements.contains(e)) issues.add(issue("MISSING_ENTITLEMENT", "entitlements", e, "application", app.id(), "entitlements"));
        return new ValidationResult(issues.stream().noneMatch(i -> i.severity() == Severity.ERROR), issues, UUID.randomUUID().toString());
    }
    private static String compatible(WorkflowStep a, WorkflowStep b, Binding binding, ProviderRegistryBoundary r) { var x = r.resolve(a.capabilityId(), a.capabilityVersion()); var y = r.resolve(b.capabilityId(), b.capabilityVersion()); if (x.isEmpty() || y.isEmpty()) return "MISSING_CAPABILITY"; if (!portMatches(binding.fromOutput(), x.get().output().name(), "output") || !portMatches(binding.toInput(), y.get().input().name(), "input")) return "INCOMPATIBLE_PORT"; if (!x.get().output().name().equals(binding.type()) || !x.get().output().name().equals(y.get().input().name()) || !x.get().output().version().equals(y.get().input().version())) return "INCOMPATIBLE_CONTRACT"; if (binding.type().endsWith("[]") && !binding.fromOutput().endsWith("[]")) return "CARDINALITY_MISMATCH"; return ""; }
    private static boolean portMatches(String actual, String expected, String kind) { return actual.equals(expected) || actual.equalsIgnoreCase(kind) || actual.equalsIgnoreCase(kind.equals("output") ? "out" : "in") || actual.equals(expected + "[]"); }
    private static void validateParameter(Parameter p, int i, String workflowId, List<ValidationIssue> issues) { String path = "parameters[" + i + "]"; Set<String> types = Set.of("string", "integer", "number", "boolean", "object", "array"); if (!types.contains(p.type().toLowerCase())) issues.add(issue("INVALID_PARAMETER_SCHEMA", path + ".type", "unsupported parameter type", "workflow", workflowId, "parameter:" + i)); if (p.minimum() != null && p.maximum() != null && p.minimum() > p.maximum()) issues.add(issue("INVALID_PARAMETER_RANGE", path, "minimum exceeds maximum", "workflow", workflowId, "parameter:" + i)); if (p.required() && p.defaultValue() == null) issues.add(issue("MISSING_PARAMETER_DEFAULT", path + ".defaultValue", "required parameter has no default", "workflow", workflowId, "parameter:" + i)); if (p.defaultValue() != null && !valueMatches(p.defaultValue(), p.type())) issues.add(issue("INVALID_PARAMETER_TYPE", path + ".defaultValue", "default value does not match parameter type", "workflow", workflowId, "parameter:" + i)); if (p.defaultValue() instanceof Number n && ((p.minimum() != null && n.doubleValue() < p.minimum()) || (p.maximum() != null && n.doubleValue() > p.maximum()))) issues.add(issue("PARAMETER_OUT_OF_RANGE", path + ".defaultValue", "default value is outside range", "workflow", workflowId, "parameter:" + i)); }
    private static boolean valueMatches(Object v, String t) { return switch (t.toLowerCase()) { case "string" -> v instanceof String; case "integer" -> v instanceof Integer || v instanceof Long; case "number" -> v instanceof Number; case "boolean" -> v instanceof Boolean; case "object" -> v instanceof Map; case "array" -> v instanceof Collection; default -> false; }; }
    private static void reach(String node, List<Binding> bs, Set<String> seen) { if (!seen.add(node)) return; bs.stream().filter(b -> b.fromStep().equals(node)).forEach(b -> reach(b.toStep(), bs, seen)); }
    public static String versionCompatibility(String range, String actual) { if (range == null || range.isBlank() || actual == null || actual.isBlank()) return "MALFORMED_VERSION_RANGE"; Semver actualVersion = Semver.parse(actual); if (actualVersion == null) return "MALFORMED_VERSION"; Semver lower=null, upper=null; boolean lowerInclusive=false, upperInclusive=false; for (String token : range.trim().split("\\s+")) { if (token.isBlank()) return "MALFORMED_VERSION_RANGE"; String op = "="; String value = token; if (token.startsWith(">=") || token.startsWith("<=") || token.startsWith(">") || token.startsWith("<") || token.startsWith("=")) { op = token.startsWith(">=") || token.startsWith("<=") ? token.substring(0, 2) : token.substring(0, 1); value = token.substring(op.length()); } Semver bound = Semver.parse(value); if (bound == null) return "MALFORMED_VERSION_RANGE"; int cmp = actualVersion.compareTo(bound); if ((op.equals("=") && cmp != 0) || (op.equals(">=") && cmp < 0) || (op.equals("<=") && cmp > 0) || (op.equals(">") && cmp <= 0) || (op.equals("<") && cmp >= 0)) return "INCOMPATIBLE_VERSION_RANGE"; if(op.equals(">")||op.equals(">=")){if(lower==null||bound.compareTo(lower)>0||(bound.compareTo(lower)==0&&op.equals(">="))){lower=bound;lowerInclusive=op.equals(">=");}} if(op.equals("<")||op.equals("<=")){if(upper==null||bound.compareTo(upper)<0||(bound.compareTo(upper)==0&&op.equals("<="))){upper=bound;upperInclusive=op.equals("<=");}} } if(lower!=null&&upper!=null&&(lower.compareTo(upper)>0||(lower.compareTo(upper)==0&&(!lowerInclusive||!upperInclusive)))) return "INVALID_VERSION_RANGE"; return "OK"; }
    private static boolean hasCycle(List<WorkflowStep> ss, List<Binding> bs) { Map<String,List<String>> g = new HashMap<>(); bs.forEach(b -> g.computeIfAbsent(b.fromStep(), k -> new ArrayList<>()).add(b.toStep())); Set<String> visiting = new HashSet<>(), done = new HashSet<>(); for (WorkflowStep s : ss) if (cycle(s.id(), g, visiting, done)) return true; return false; }
    private static boolean cycle(String n, Map<String,List<String>> g, Set<String> v, Set<String> d) { if (v.contains(n)) return true; if (d.contains(n)) return false; v.add(n); for (String x : g.getOrDefault(n, List.of())) if (cycle(x, g, v, d)) return true; v.remove(n); d.add(n); return false; }
    private record Semver(int major, int minor, int patch, String pre) implements Comparable<Semver> { static Semver parse(String value) { Matcher m = Pattern.compile("^(\\d+)\\.(\\d+)(?:\\.(\\d+))?(?:-([0-9A-Za-z.-]+))?$").matcher(value); if (!m.matches()) return null; return new Semver(Integer.parseInt(m.group(1)), Integer.parseInt(m.group(2)), m.group(3) == null ? 0 : Integer.parseInt(m.group(3)), m.group(4)); } public int compareTo(Semver o) { int c = Comparator.comparingInt(Semver::major).thenComparingInt(Semver::minor).thenComparingInt(Semver::patch).compare(this, o); if (c != 0) return c; if (pre == null && o.pre != null) return 1; if (pre != null && o.pre == null) return -1; if (Objects.equals(pre,o.pre)) return 0; String[] a=pre.split("\\."), b=o.pre.split("\\."); for(int i=0;i<Math.max(a.length,b.length);i++){if(i>=a.length)return -1;if(i>=b.length)return 1;boolean an=a[i].matches("\\d+"),bn=b[i].matches("\\d+");if(an&&bn){int z=Integer.compare(Integer.parseInt(a[i]),Integer.parseInt(b[i]));if(z!=0)return z;}else if(an!=bn)return an?-1:1;else {int z=a[i].compareTo(b[i]);if(z!=0)return z;}}return 0; } }
}
