package com.example.platform.execution.composition;

/** Frozen typed blocker algebra for provider-local execution lowering. */
public enum CompositionBlocker {
    MANDATORY_INTERMEDIATE_ARTIFACT,
    PROVIDER_NATIVE_PIPELINE_UNSUPPORTED,
    DEVICE_CONTEXT_INCOMPATIBLE,
    SOFTWARE_HARDWARE_FRAME_BOUNDARY,
    SANDBOX_OR_TRUST_BOUNDARY,
    BRANCHING_SEMANTIC_BOUNDARY,
    RETRY_OR_FAILURE_ISOLATION_BOUNDARY,
    DETERMINISM_INCOMPATIBLE,
    INPUT_OUTPUT_CONTRACT_INCOMPATIBLE,
    UNKNOWN_PROVIDER_COMPOSITION_SEMANTICS
}
