import api from './index'

export type CapabilityAvailability = { capabilityId:string; version:string; input:{name:string;version:string}; output:{name:string;version:string}; assetTypes:string[]; mediaTypes:string[]; executionModes:string[]; availability:string; summary:string; estimate:{units:number;unit:string;quotaUnits:number}; reliability:{cancellable:boolean;retryable:boolean;maxRetries:number} }
export type WorkflowDraft = { id:string; version:string; name:string; steps:any[]; bindings:any[]; parameters:any[]; requiredCapabilities:string[]; executionModes:string[]; requiredAssets:string[]; outputs:any[]; estimate:any; reliability:any; lifecycle:string; tenantId:string; workspaceId:string; revision:number }
export type ApplicationDraft = { id:string; version:string; displayName:string; description:string; input:any; output:any; requiredCapabilities:string[]; workflowIds:string[]; requiredAssets:string[]; entitlements:string[]; executionModes:string[]; lifecycle:string; tenantId:string; workspaceId:string; revision:number }
export type ValidationIssue = { code:string; severity:'ERROR'|'WARNING'; objectType:string; objectId:string; path:string; location:string; message:string }
export type ValidationResult = { ready:boolean; issues:ValidationIssue[]; snapshotId:string }
const request = { baseURL:'/api' }
export const compositionApi = { async capabilities(workspaceId:string){ return (await api.get<CapabilityAvailability[]>('/composition/capabilities',{...request,params:{workspaceId}})).data }, async getWorkflow(workspaceId:string,id='composition-workflow'){ return (await api.get<WorkflowDraft>(`/composition/workflows/drafts/${id}`,{...request,params:{workspaceId}})).data }, async saveWorkflow(v:WorkflowDraft){ return (await api.post<WorkflowDraft>('/composition/workflows/drafts',v,request)).data }, async validateWorkflow(v:WorkflowDraft){ return (await api.post<ValidationResult>('/composition/workflows/publish-readiness',v,request)).data }, async getApplication(workspaceId:string,id='composition-application'){ return (await api.get<ApplicationDraft>(`/composition/applications/drafts/${id}`,{...request,params:{workspaceId}})).data }, async saveApplication(v:ApplicationDraft){ return (await api.post<ApplicationDraft>('/composition/applications/drafts',v,request)).data }, async validateApplication(v:ApplicationDraft){ return (await api.post<ValidationResult>('/composition/applications/publish-readiness',v,request)).data } }
