apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: media-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/platform"
  SPRING_DATASOURCE_USERNAME: "platform"
  SPRING_FLYWAY_ENABLED: "true"
  APP_SECURITY_ENABLED: "true"
  APP_SECURITY_OAUTH2_ENABLED: "true"
  APP_STORAGE_LOCAL_ROOT: "/data/platform"
  SERVER_PORT: "8080"
