apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: media-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
  APP_JWT_SECRET: "CHANGE_ME_TO_STRONG_SECRET_MIN_256_BITS"
  APP_SECURITY_OAUTH2_ISSUER_URI: "https://auth.example.com"
  APP_SECURITY_OAUTH2_AUDIENCE: "media-platform"
  STRIPE_WEBHOOK_SECRET: "CHANGE_ME"
  HYPER_SWITCH_WEBHOOK_SECRET: "CHANGE_ME"
