@org.springframework.modulith.ApplicationModule(
        allowedDependencies = {"audit-ports :: api",
        "marketplace :: api","media :: assets",
            "timeline :: reviews", "timeline :: revision", "timeline :: composition", "timeline :: serialization",
            "shared",
            "identity :: authorization",
            "observability :: context",
            "entitlement :: collaboration",
            "render",
            "render :: requests", "render :: API",
            "render :: app",
            "render :: domain",
            "render :: timeline",
            "render :: infrastructure",
            "identity",
            "identity :: app",
            "identity :: domain",
            "identity :: infrastructure",
            "prompt",
            "prompt :: app",
            "prompt :: domain",
            "billing",
            "billing :: app",
            "billing :: domain",
            "entitlement",
            "entitlement :: app",
            "entitlement :: domain",
            "artifact",
            "artifact :: app",
            "artifact :: domain",
            "audit",
            "audit :: app",
            "storage",
            "storage :: API",
            "storage :: domain",
            "storage :: infrastructure",
            "delivery",
            "delivery :: API",
            "delivery :: app",
            "social",
            "social :: app",
            "policy",
            "policy :: feature-flags",
            "commerce",
            "commerce :: app",
            "commerce :: domain",
            "commerce :: infrastructure",
            "app",
            "app :: ai",
            "security",
            "workflow",
            "workflow :: temporal",
            "observability :: monitoring"
        })
package com.example.platform.web;
