@org.springframework.modulith.ApplicationModule(
        allowedDependencies = {
            "shared",
            "render",
            "render :: API",
            "render :: app",
            "render :: domain",
            "render :: timeline",
            "render :: infrastructure",
            "identity :: app",
            "identity :: domain",
            "identity :: infrastructure",
            "prompt :: app",
            "prompt :: domain",
            "billing :: app",
            "billing :: domain",
            "entitlement :: app",
            "entitlement :: domain",
            "artifact",
            "artifact :: app",
            "audit :: app",
            "storage",
            "storage :: API",
            "storage :: domain",
            "delivery :: API",
            "delivery :: app",
            "policy :: feature-flags",
            "commerce",
            "commerce :: app",
            "commerce :: domain",
            "commerce :: infrastructure",
            "app",
            "app :: ai",
            "security",
            "workflow",
            "workflow :: temporal",
            "artifact :: domain",
            "storage :: infrastructure"
        })
package com.example.platform.web;
