package com.example.platform.audit.app;

public enum AuditCategory {
    CONFIG,
    PROMPT,
    POLICY,
    PLUGIN,
    MANUAL_RETRY,
    PERMISSION,
    EXTENSION,
    EXTENSION_ROUTING,
    EXTENSION_RESOURCE,
    SANDBOX,
    ENTITLEMENT,
    GRAPHQL_OPERATION,
    PROVIDER_HEALTH,
    API_REQUEST,
    FEATURE_FLAG,
    NLQ,
    GENERAL,
    RENDER,
    DATA_GOVERNANCE,
    IDENTITY,
    ADMIN_AUDIT,
    UNKNOWN
}
