package com.example.platform.render.domain.timeline.diff.merge;

/**
 * Code identifying the type of merge conflict issue.
 * Internal domain model. Provider-neutral, storage-neutral.
 */
public enum TimelineMergeConflictIssueCode {
    MISSING_BASE,
    MISSING_OURS,
    MISSING_THEIRS,
    BASE_REVISION_MISMATCH,
    UNSUPPORTED_CHANGE_TYPE,
    SAME_PATH_DIVERGENT_CHANGE,
    TARGET_REMOVED_AND_MODIFIED,
    TARGET_REMOVED_AND_MOVED,
    TRACK_ORDER_DIVERGENCE,
    CLIP_TIMING_OVERLAP,
    CAPTION_TEXT_DIVERGENCE,
    TEXT_STYLE_DIVERGENCE,
    WATERMARK_POSITION_DIVERGENCE,
    TEMPLATE_PARAMETER_DIVERGENCE,
    TEMPLATE_PROFILE_DIVERGENCE,
    WORKFLOW_STEP_DIVERGENCE,
    OUTPUT_PROFILE_DIVERGENCE,
    RENDER_IMPACT_DIVERGENCE,
    PROVIDER_INTERNALS_NOT_ALLOWED,
    STORAGE_INTERNALS_NOT_ALLOWED,
    EXECUTION_NOT_ALLOWED
}
