package com.example.platform.ingest.contract;

public enum IngestRejectionReasonCode {
    FILE_EMPTY,
    FILE_TOO_LARGE,
    CONTENT_TYPE_UNSUPPORTED,
    CONTENT_TYPE_BLOCKED,
    EXTENSION_BLOCKED,
    DECLARED_CONTENT_TYPE_CONFLICT,
    DETECTED_CONTENT_TYPE_CONFLICT,
    MEDIA_PROBE_FAILED,
    MEDIA_DURATION_TOO_LONG,
    MEDIA_CODEC_UNSUPPORTED,
    MEDIA_RESOLUTION_UNSUPPORTED,
    ARCHIVE_NOT_ALLOWED,
    ARCHIVE_EXPANSION_LIMIT_EXCEEDED,
    PARSING_TIMEOUT,
    PARSING_RESOURCE_LIMIT_EXCEEDED,
    SECURITY_SCAN_FAILED,
    SECURITY_SCAN_REQUIRED,
    UNKNOWN_CONTENT_POLICY
}
