package com.example.platform.ingest.contract;

public enum IngestWarningCode {
    DECLARED_CONTENT_TYPE_MISMATCH,
    EXTENSION_CONTENT_TYPE_MISMATCH,
    UNKNOWN_CONTENT_TYPE,
    UNSUPPORTED_CONTENT_TYPE,
    DETECTION_LOW_CONFIDENCE,
    DETECTION_LIMIT_REACHED,
    EMPTY_FILE,
    MISSING_FILENAME,
    MISSING_EXTENSION,
    SUSPICIOUS_EXTENSION,
    MULTIPLE_EXTENSIONS,
    POSSIBLE_ARCHIVE_BOMB,
    METADATA_TRUNCATED,
    RAW_METADATA_DROPPED,
    TEXT_EXTRACTION_DISABLED,
    OCR_DISABLED,
    MEDIA_TECHNICAL_METADATA_MISSING
}
