-- Test schema: combines all V1-V8 Flyway migrations for H2

-- V1 tables
create table if not exists render_job (
    id varchar(64) primary key,
    project_id varchar(128) not null,
    tenant_id varchar(64),
    timeline_snapshot_id varchar(128) not null,
    profile varchar(128) not null,
    status varchar(32) not null,
    ai_script text,
    artifact_uri text,
    error_message text,
    created_at timestamp not null
);

create table if not exists render_job_status_history (
    id varchar(64) primary key,
    job_id varchar(64) not null,
    from_status varchar(30),
    to_status varchar(30) not null,
    reason varchar(255),
    error_code varchar(100),
    occurred_at timestamp not null
);

create table if not exists notification_event (
    id varchar(64) primary key,
    event_type varchar(128) not null,
    subject_id varchar(128),
    payload text not null,
    created_at timestamp not null
);

create table if not exists notification_template (
    id bigint generated by default as identity primary key,
    template_code varchar(64) not null,
    channel varchar(32) not null,
    locale varchar(16) not null,
    version int not null,
    subject_template varchar(255),
    body_template text not null
);

create table if not exists notification_delivery (
    id varchar(64) primary key,
    event_id varchar(64) not null,
    channel varchar(32) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    request_payload text,
    response_payload text,
    attempt_count int not null,
    created_at timestamp not null
);

create table if not exists config_item (
    id bigint generated by default as identity primary key,
    namespace_key varchar(128) not null,
    config_key varchar(128) not null,
    value_json text not null,
    value_version int not null,
    updated_at timestamp not null
);

-- V2 tables
create table if not exists storage_object (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    bucket varchar(128) not null,
    object_key text not null,
    content_type varchar(255),
    checksum_sha256 varchar(128),
    file_size_bytes bigint,
    lifecycle_policy varchar(64),
    created_at timestamp not null
);

create table if not exists prompt_template (
    id varchar(64) primary key,
    template_code varchar(128) not null,
    locale varchar(32) not null,
    version int not null,
    template_body text not null,
    variables_schema text,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists prompt_execution_log (
    id varchar(64) primary key,
    template_code varchar(128) not null,
    template_version int,
    provider_code varchar(64),
    model_code varchar(128),
    variables_json text,
    rendered_prompt text,
    created_at timestamp not null
);

create table if not exists cloud_resource_definition (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    resource_type varchar(64) not null,
    logical_name varchar(128) not null,
    spec_json text not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists secret_ref (
    id varchar(64) primary key,
    namespace_key varchar(128) not null,
    secret_key varchar(128) not null,
    backend_type varchar(64) not null,
    backend_ref varchar(255) not null,
    created_at timestamp not null
);

create table if not exists extension_definition (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_type varchar(64) not null,
    language varchar(32),
    runtime varchar(64),
    version varchar(64) not null,
    artifact_uri text,
    status varchar(32) not null,
    timeout_ms bigint,
    config_schema text,
    created_at timestamp not null
);

create table if not exists extension_invocation (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_version varchar(64) not null,
    caller_module varchar(128) not null,
    input_summary text,
    output_summary text,
    exit_status varchar(32),
    duration_ms bigint,
    created_at timestamp not null
);

create table if not exists app_datasource (
    id varchar(64) primary key,
    datasource_code varchar(64) not null,
    datasource_kind varchar(32) not null,
    dialect varchar(32),
    jdbc_url text,
    secret_ref varchar(255),
    is_primary boolean not null,
    usage_role varchar(64) not null,
    created_at timestamp not null
);

-- V3 tables
create table if not exists outbox_events (
    id varchar(64) primary key,
    aggregate_type varchar(100) not null,
    aggregate_id varchar(100) not null,
    event_type varchar(150) not null,
    event_version int not null,
    payload text not null,
    status varchar(50) not null,
    retry_count int not null default 0,
    next_attempt_at timestamp,
    idempotency_key varchar(255),
    created_at timestamp not null,
    published_at timestamp
);

create table if not exists audit_records (
    id varchar(64) primary key,
    actor_type varchar(50) not null,
    actor_id varchar(100),
    action varchar(120) not null,
    resource_type varchar(120) not null,
    resource_id varchar(120),
    payload text,
    category varchar(50),
    created_at timestamp not null
);

create table if not exists schedules (
    id varchar(64) primary key,
    schedule_code varchar(100) not null,
    handler_code varchar(120) not null,
    enabled boolean not null,
    created_at timestamp not null
);

create table if not exists quota_definitions (
    id varchar(64) primary key,
    quota_code varchar(80) not null,
    unit varchar(50) not null,
    created_at timestamp not null
);

-- V4 tables
create table if not exists commerce_product (
    id varchar(64) primary key,
    product_code varchar(128) not null,
    name varchar(255) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists commerce_price (
    id varchar(64) primary key,
    product_id varchar(64) not null,
    currency varchar(3) not null,
    amount bigint not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists provider_product_mapping (
    id varchar(64) primary key,
    product_id varchar(64) not null,
    provider_code varchar(64) not null,
    external_id varchar(255) not null,
    created_at timestamp not null
);

create table if not exists checkout_session (
    id varchar(64) primary key,
    product_id varchar(64) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists purchase_order (
    id varchar(64) primary key,
    checkout_session_id varchar(64) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists payment_attempt (
    id varchar(64) primary key,
    purchase_order_id varchar(64) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists provider_webhook_event (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    event_type varchar(128) not null,
    payload text not null,
    created_at timestamp not null
);

create table if not exists subscription_contract (
    id varchar(64) primary key,
    subject_type varchar(64) not null,
    subject_id varchar(64) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists billing_invoice (
    id varchar(64) primary key,
    contract_id varchar(64) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists feature_definition (
    id varchar(64) primary key,
    feature_code varchar(128) not null,
    name varchar(255) not null,
    created_at timestamp not null
);

create table if not exists feature_bundle (
    id varchar(64) primary key,
    bundle_code varchar(128) not null,
    name varchar(255) not null,
    created_at timestamp not null
);

create table if not exists feature_bundle_item (
    id varchar(64) primary key,
    bundle_id varchar(64) not null,
    feature_id varchar(64) not null,
    created_at timestamp not null
);

create table if not exists entitlement_grant (
    id varchar(64) primary key,
    subject_type varchar(64) not null,
    subject_id varchar(64) not null,
    feature_id varchar(64) not null,
    created_at timestamp not null
);

create table if not exists entitlement_override (
    id varchar(64) primary key,
    subject_type varchar(64) not null,
    subject_id varchar(64) not null,
    feature_id varchar(64) not null,
    created_at timestamp not null
);

-- V7 tables
create table if not exists tenant (
    id varchar(64) primary key,
    name varchar(255) not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create table if not exists project (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    name varchar(255) not null,
    description text,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create table if not exists "user" (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    username varchar(128) not null,
    email varchar(255) not null,
    role varchar(32) not null default 'MEMBER',
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create table if not exists api_key (
    id varchar(64) primary key,
    tenant_id varchar(64),
    fingerprint varchar(32) not null,
    hashed_key varchar(128) not null,
    principal varchar(255) not null,
    created_at timestamp not null,
    last_used_at timestamp,
    revoked_at timestamp
);

create table if not exists artifact (
    id varchar(64) primary key,
    render_job_id varchar(64) not null,
    project_id varchar(64) not null,
    storage_uri text not null,
    format varchar(32),
    resolution varchar(32),
    duration bigint,
    created_at timestamp not null
);

create table if not exists notification_record (
    id varchar(64) primary key,
    event_id varchar(64) not null,
    channel varchar(32) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    subject varchar(512),
    body text,
    metadata_json text,
    attempt_count int not null default 1,
    created_at timestamp not null
);

-- V8 tables
create table if not exists quota_usage (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    feature_code varchar(80) not null,
    usage_value int not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null
);
