package com.example.platform.render.domain.timeline.render.transition;

/**
 * Issue codes for FFmpeg baseline transition planning.
 * Immutable enum. Internal domain model.
 */
public enum FFmpegBaselineTransitionPlanIssueCode {
    INVALID_REQUEST,
    INVALID_TIMELINE,
    TRANSITION_NOT_FOUND,
    TRANSITION_CLIP_NOT_FOUND,
    TRANSITION_FROM_CLIP_NOT_FOUND,
    TRANSITION_TO_CLIP_NOT_FOUND,
    TRANSITION_CAPABILITY_NOT_FOUND,
    TRANSITION_CAPABILITY_UNSUPPORTED,
    TRANSITION_CAPABILITY_FORBIDDEN,
    TRANSITION_CAPABILITY_RESTRICTED,
    TRANSITION_CAPABILITY_POC_ONLY,
    INVALID_TRANSITION_DURATION,
    INVALID_TRANSITION_PARAMETER,
    MISSING_REQUIRED_PARAMETER,
    UNSUPPORTED_PARAMETER,
    INVALID_OPERATION_TARGET,
    NON_ADJACENT_CLIPS,
    OVERLAP_REQUIRED_BUT_MISSING,
    INSUFFICIENT_CLIP_DURATION,
    RAW_FILTERGRAPH_FORBIDDEN,
    RAW_PROVIDER_COMMAND_FORBIDDEN,
    USER_RENDER_DAG_FORBIDDEN,
    PLUGIN_EXECUTION_NODE_FORBIDDEN,
    REMOTION_EXECUTION_FORBIDDEN,
    ARTIFACT_DAG_NOT_USED,
    RENDER_NOT_ALLOWED,
    PRODUCT_CREATION_NOT_ALLOWED,
    STORAGE_INTERNALS_FORBIDDEN,
    PROVIDER_INTERNALS_FORBIDDEN,
    PERSISTENCE_NOT_IMPLEMENTED
}
