import { useEffect, useMemo, useState } from 'react'
import { compositionApi, type CapabilityAvailability, type WorkflowDraft, type ApplicationDraft, type ValidationIssue } from '../api/composition'
import { useWorkspaceBinding } from '../foundation/workspaceSession'

const emptyWorkflow=(workspaceId:string,id='composition-workflow'):WorkflowDraft=>({id,version:'1.0',name:'New workflow',steps:[],bindings:[],parameters:[],requiredCapabilities:[],executionModes:['ASYNCHRONOUS'],requiredAssets:[],outputs:[],estimate:{units:0,unit:'quota-unit',quotaUnits:0},reliability:{cancellable:true,retryable:true,maxRetries:1},lifecycle:'DRAFT',tenantId:'',workspaceId,revision:0})
const emptyApplication=(workspaceId:string):ApplicationDraft=>({id:'composition-application',version:'1.0',displayName:'New application',description:'',input:{name:'MediaAsset',version:'1'},output:{name:'MediaAsset',version:'1'},requiredCapabilities:[],workflowIds:['composition-workflow'],requiredAssets:[],entitlements:['composition.create'],executionModes:['ASYNCHRONOUS'],lifecycle:'DRAFT',tenantId:'',workspaceId,revision:0})
type Recovery<T> = { state:'present'; value:T } | { state:'missing'; id:string } | { state:'error'; id:string; status?:number; message:string }
async function recover<T>(load:()=>Promise<T>, id:string):Promise<Recovery<T>> { try { return {state:'present',value:await load()} } catch (e:any) { const status=e?.response?.status; if(status===404)return {state:'missing',id}; return {state:'error',id,status,message:message(e,'Unable to restore draft')} } }
function key(workspaceId:string){return `composition-validation:${workspaceId}`}
function formatRecovery(kind:string,result:Recovery<unknown>){if(result.state==='missing')return `${kind} ${result.id} is missing or deleted; restore it or choose another resource.`; if(result.state==='error')return `${kind} ${result.id} could not be restored (${result.status??'network error'}): ${result.message}`; return ''}
function message(e:any,fallback:string){return e?.response?.status===401?'Session expired':e?.response?.status===403?'Workspace access denied':e?.response?.status===404?'Draft no longer exists':e?.response?.status===409?'Draft changed elsewhere':fallback}
export function CompositionFoundationPage(){
 const {binding,retired}=useWorkspaceBinding(); const [capabilities,setCapabilities]=useState<CapabilityAvailability[]>([]); const [workflows,setWorkflows]=useState<Record<string,WorkflowDraft>>({}); const [activeId,setActiveId]=useState('composition-workflow'); const [application,setApplication]=useState<ApplicationDraft>(()=>emptyApplication(binding.workspaceId)); const [applicationMode,setApplicationMode]=useState(false); const [status,setStatus]=useState(''); const [issues,setIssues]=useState<ValidationIssue[]>([]); const [recovery,setRecovery]=useState<string[]>([]); const [focused,setFocused]=useState('');
 const workflow=workflows[activeId]??emptyWorkflow(binding.workspaceId,activeId); const selected=workflow.requiredCapabilities??[]; const available=useMemo(()=>new Map(capabilities.map(c=>[c.capabilityId,c])),[capabilities]);
 useEffect(()=>{if(!binding.workspaceId)return; let live=true; try{const saved=sessionStorage.getItem(key(binding.workspaceId));if(saved)setIssues(JSON.parse(saved))}catch{setStatus('Saved validation issues could not be restored')}
  void (async()=>{const catalog=await recover(()=>compositionApi.capabilities(binding.workspaceId),'capabilities'); const app=await recover(()=>compositionApi.getApplication(binding.workspaceId),'application'); const appValue=app.state==='present'?app.value:emptyApplication(binding.workspaceId); const ids=[...new Set(appValue.workflowIds.length?appValue.workflowIds:['composition-workflow'])]; const loaded=await Promise.all(ids.map(id=>recover(()=>compositionApi.getWorkflow(binding.workspaceId,id),id))); if(!live)return; const notices:string[]=[]; if(catalog.state==='present')setCapabilities(catalog.value);else notices.push(formatRecovery('capabilities',catalog)); if(app.state==='present'){setApplication(app.value);setApplicationMode(true)}else notices.push(formatRecovery('application',app)); const restored:Record<string,WorkflowDraft>={}; loaded.forEach(x=>{if(x.state==='present')restored[x.value.id]=x.value;else notices.push(formatRecovery('workflow',x))}); setWorkflows(restored); const first=Object.keys(restored)[0]??ids[0];setActiveId(first);setRecovery(notices);if(notices.length)setStatus('Some composition resources need recovery')})(); return()=>{live=false}},[binding.workspaceId]);
 const updateWorkflow=(fn:(w:WorkflowDraft)=>WorkflowDraft)=>setWorkflows(ws=>({...ws,[activeId]:fn(workflow)}));
 function toggleCapability(id:string,checked:boolean){updateWorkflow(w=>({...w,requiredCapabilities:checked?[...w.requiredCapabilities,id]:w.requiredCapabilities.filter(x=>x!==id),steps:checked?[...w.steps,{id:`step-${w.steps.length}`,capabilityId:id,capabilityVersion:available.get(id)?.version??'1.0',inputs:{},requiredAssets:[],alternatives:[]}]:w.steps.filter(s=>s.capabilityId!==id)}))}
 async function save(){try{const v=await compositionApi.saveWorkflow({...workflow,workspaceId:binding.workspaceId});setWorkflows(ws=>({...ws,[v.id]:v}));setStatus('Workflow draft saved')}catch(e:any){setStatus(message(e,'Save failed'))}}
 async function saveApplication(){try{const v=await compositionApi.saveApplication({...application,workspaceId:binding.workspaceId,requiredCapabilities:[...new Set(Object.values(workflows).flatMap(w=>w.requiredCapabilities))],workflowIds:Object.keys(workflows),executionModes:workflow.executionModes,requiredAssets:[...new Set(Object.values(workflows).flatMap(w=>w.requiredAssets))]});setApplication(v);setStatus('Application draft saved')}catch(e:any){setStatus(message(e,'Application save failed'))}}
 async function validate(){try{const r=applicationMode?await compositionApi.validateApplication({...application,workspaceId:binding.workspaceId,workflowIds:Object.keys(workflows)}):await compositionApi.validateWorkflow({...workflow,workspaceId:binding.workspaceId});setIssues(r.issues??[]);try{sessionStorage.setItem(key(binding.workspaceId),JSON.stringify(r.issues??[]))}catch{setStatus('Validation completed; issues could not be persisted locally')}setStatus(r.ready?'Ready to publish':`${(r.issues??[]).length} validation issue(s)`)}catch(e:any){setStatus(message(e,'Validation failed'))}}
 function focusIssue(issue:ValidationIssue){const loc=issue.location||issue.path;setFocused(loc);const target=document.querySelector<HTMLElement>(`[data-editor-id="${loc}"]`)||document.querySelector<HTMLElement>(`[data-editor-id="${issue.path}"]`);target?.focus();target?.scrollIntoView({block:'center'})}
 if(retired)return <main className="foundation-page"><p role="alert">Your session expired. Sign in again to continue.</p></main>
 const grouped=issues.reduce<[string,ValidationIssue[]][]>((g,i)=>{const k=`${i.objectType}:${i.objectId||'composition'}`;const x=g.find(v=>v[0]===k);if(x)x[1].push(i);else g.push([k,[i]]);return g},[])
 return <main className="foundation-page"><h1>Composition foundation</h1><p>Workspace: {binding.workspaceId}</p>{recovery.length>0&&<section aria-label="Draft recovery"><h2>Recovery needed</h2><ul>{recovery.map(x=><li key={x}>{x}</li>)}</ul></section>}
  <label>Workflow <select aria-label="Workflow draft" value={activeId} onChange={e=>setActiveId(e.target.value)}>{Object.keys(workflows).map(id=><option key={id}>{id}</option>)}</select></label>
  <label>Workflow name <input data-editor-id="name" value={workflow.name} onChange={e=>updateWorkflow(w=>({...w,name:e.target.value}))}/></label><label><input type="checkbox" checked={applicationMode} onChange={e=>setApplicationMode(e.target.checked)}/> Compose an Application</label>
  <h2>Available capabilities</h2><ul>{capabilities.map(c=><li key={`${c.capabilityId}:${c.version}`}><label><input data-editor-id={`capability:${c.capabilityId}`} type="checkbox" checked={selected.includes(c.capabilityId)} onChange={e=>toggleCapability(c.capabilityId,e.target.checked)}/>{c.capabilityId} v{c.version} — {c.summary} ({c.availability})</label></li>)}</ul>
  <label>Required assets <input data-editor-id="requiredAssets" aria-label="Required assets" value={(workflow.requiredAssets??[]).join(',')} onChange={e=>updateWorkflow(w=>({...w,requiredAssets:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}))}/></label>
  {(workflow.steps??[]).map(s=><fieldset key={s.id} data-editor-id={`node:${s.id}`}><legend>{s.id}</legend><label>Parameters <input data-editor-id={`parameter:${s.id}`} aria-label={`${s.id} parameters`}/></label><label>Bindings <input data-editor-id={`binding:${s.id}`} aria-label={`${s.id} bindings`}/></label></fieldset>)}
  {applicationMode&&<><label>Application name <input data-editor-id="application:displayName" value={application.displayName} onChange={e=>setApplication(a=>({...a,displayName:e.target.value}))}/></label><label>Entitlements <input data-editor-id="application:entitlements" aria-label="Entitlements" value={application.entitlements.join(',')} onChange={e=>setApplication(a=>({...a,entitlements:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}))}/></label></>}
  <p>Estimated quota: {workflow.estimate?.quotaUnits??0} unit(s)</p><button onClick={applicationMode?saveApplication:save}>Save draft</button><button onClick={validate}>Check publish readiness</button>{status&&<p role="status">{status}</p>}
  <section aria-label="Validation issues"><h2>Validation issues</h2>{grouped.map(([group,gi])=><section key={group}><h3>{group}</h3><ul>{gi.map((x,i)=><li key={`${x.code}-${x.path}-${i}`}><button type="button" aria-label={`Go to ${x.location||x.path}`} aria-current={focused===(x.location||x.path)} onClick={()=>focusIssue(x)}>{x.severity} {x.code} {x.path}: {x.message}</button></li>)}</ul></section>)}</section></main>
}
