import { useEffect, useState } from 'react'
import { compositionApi, type CapabilityAvailability, type WorkflowDraft, type ApplicationDraft } from '../api/composition'
import { useWorkspaceBinding } from '../foundation/workspaceSession'

export function CompositionFoundationPage() {
  const { binding, retired } = useWorkspaceBinding()
  const [capabilities,setCapabilities]=useState<CapabilityAvailability[]>([]); const [selected,setSelected]=useState<string[]>([]); const [status,setStatus]=useState(''); const [name,setName]=useState('New workflow'); const [applicationMode,setApplicationMode]=useState(false); const [entitlement,setEntitlement]=useState('composition.create'); const [workflowRevision,setWorkflowRevision]=useState(0); const [applicationRevision,setApplicationRevision]=useState(0)
  useEffect(()=>{if(binding.workspaceId) compositionApi.capabilities(binding.workspaceId).then(setCapabilities).catch(e=>setStatus(e?.response?.status===401?'Session expired':e?.response?.status===403?'Workspace access denied':'Unable to load catalog'))},[binding.workspaceId])
  useEffect(()=>{if(binding.workspaceId) compositionApi.getWorkflow(binding.workspaceId).then(v=>{setName(v.name);setSelected(v.requiredCapabilities);setWorkflowRevision(v.revision)}).catch(e=>{if(e?.response?.status===401)setStatus('Session expired')})},[binding.workspaceId])
  const draft: WorkflowDraft={id:'composition-workflow',version:'1.0',name,steps:selected.map((id,i)=>({id:'step-'+i,capabilityId:id,capabilityVersion:'1.0',inputs:{},requiredAssets:[],alternatives:[]})),bindings:[],parameters:[],requiredCapabilities:selected,executionModes:['ASYNCHRONOUS'],requiredAssets:[],estimate:{units:selected.length,unit:'quota-unit',quotaUnits:selected.length},reliability:{cancellable:true,retryable:true,maxRetries:1},lifecycle:'DRAFT',tenantId:'',workspaceId:binding.workspaceId,revision:workflowRevision}
  const application: ApplicationDraft={id:'composition-application',version:'1.0',displayName:name,description:'',input:{name:'MediaAsset',version:'1'},output:{name:'MediaAsset',version:'1'},requiredCapabilities:selected,workflowIds:['composition-workflow'],requiredAssets:[],entitlements:[entitlement],executionModes:['ASYNCHRONOUS'],lifecycle:'DRAFT',tenantId:'',workspaceId:binding.workspaceId,revision:applicationRevision}
  async function save(){try{const v=await compositionApi.saveWorkflow(draft);setWorkflowRevision(v.revision);setStatus('Draft saved')}catch(e:any){setStatus(e?.response?.status===401?'Session expired':e?.response?.status===403?'Workspace access denied':e?.response?.status===409?'Draft changed elsewhere':'Save failed')}}
  async function validate(){try{const r=await compositionApi.validateWorkflow(draft);setStatus(r.ready?'Ready to publish':r.issues.map((x:any)=>x.code).join(', '))}catch{setStatus('Validation failed')}}
  async function saveApplication(){try{const v=await compositionApi.saveApplication(application);setApplicationRevision(v.revision);setStatus('Application draft saved')}catch(e:any){setStatus(e?.response?.status===401?'Session expired':e?.response?.status===403?'Workspace access denied':e?.response?.status===409?'Draft changed elsewhere':'Application save failed')}}
  if (retired) return <main className="foundation-page"><p role="alert">Your session expired. Sign in again to continue.</p></main>
  return <main className="foundation-page"><h1>Composition foundation</h1><p>Workspace: {binding.workspaceId}</p><p>Browse capabilities and build a provider-neutral composition.</p><label>Display name <input value={name} onChange={e=>setName(e.target.value)} /></label><label><input type="checkbox" checked={applicationMode} onChange={e=>setApplicationMode(e.target.checked)}/> Compose an Application from this workflow</label><h2>Available capabilities</h2><ul>{capabilities.map(c=><li key={c.capabilityId}><label><input type="checkbox" checked={selected.includes(c.capabilityId)} onChange={e=>setSelected(v=>e.target.checked?[...v,c.capabilityId]:v.filter(x=>x!==c.capabilityId))}/>{c.capabilityId} v{c.version} — {c.summary} ({c.availability})</label></li>)}</ul>{applicationMode&&<label>Required entitlement <input value={entitlement} onChange={e=>setEntitlement(e.target.value)}/></label>}<button onClick={applicationMode?saveApplication:save}>Save draft</button><button onClick={validate}>Check publish readiness</button><p>Estimated quota: {selected.length} unit(s)</p>{status&&<p role="status">{status}</p>}</main>
}
