import { describe, expect, it, vi, beforeEach } from 'vitest'
import { render, screen, waitFor, fireEvent } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { WorkspaceSessionProvider } from '../foundation/workspaceSession'
import { CompositionFoundationPage } from './CompositionFoundationPage'
import { compositionApi } from '../api/composition'
vi.mock('../api/composition', async () => { const actual = await vi.importActual<typeof import('../api/composition')>('../api/composition'); return { ...actual, compositionApi: { ...actual.compositionApi } } })
const workflow={id:'wf',version:'1.0',name:'Restored workflow',steps:[{id:'step-0',capabilityId:'media.thumbnail',capabilityVersion:'1.0',inputs:{},requiredAssets:[],alternatives:[]}],bindings:[{fromStep:'step-0',fromOutput:'output',toStep:'step-0',toInput:'input',type:'ImageAsset'}],parameters:[{name:'quality',type:'integer',defaultValue:1,minimum:0,maximum:2,required:false}],requiredCapabilities:[],executionModes:['ASYNCHRONOUS'],requiredAssets:['asset'],outputs:[{name:'result',type:'ImageAsset',stepId:'step-0',port:'output'}],entry:{name:'input',contract:{name:'MediaAsset',version:'1'},stepId:'step-0',port:'input'},estimate:{units:0,unit:'u',quotaUnits:0},reliability:{cancellable:true,retryable:true,maxRetries:1},lifecycle:'DRAFT',tenantId:'t',workspaceId:'w',revision:4}
const capability={capabilityId:'media.thumbnail',version:'1.0',input:{name:'MediaAsset',version:'1'},output:{name:'ImageAsset',version:'1'},assetTypes:[],mediaTypes:[],executionModes:['ASYNCHRONOUS'],availability:'AVAILABLE',summary:'Thumbnail',estimate:{units:1,unit:'u',quotaUnits:1},reliability:{cancellable:true,retryable:true,maxRetries:1}}
function http(status:number){return Object.assign(new Error(`HTTP ${status}`),{response:{status}})}
function renderPage(){return render(<QueryClientProvider client={new QueryClient()}><WorkspaceSessionProvider workspaceId="w"><CompositionFoundationPage/></WorkspaceSessionProvider></QueryClientProvider>)}
describe('composition draft recovery',()=>{ beforeEach(()=>{sessionStorage.clear(); vi.restoreAllMocks(); vi.spyOn(compositionApi,'capabilities').mockResolvedValue([capability] as any); vi.spyOn(compositionApi,'getWorkflow').mockResolvedValue(workflow as any); vi.spyOn(compositionApi,'getApplication').mockRejectedValue(http(404))})
 it('restores workflow and catalog when application draft is missing',async()=>{renderPage(); await waitFor(()=>expect(screen.getByDisplayValue('Restored workflow')).toBeTruthy()); expect(screen.getByText(/application application is missing or deleted/)).toBeTruthy(); expect(screen.getByText(/media\.thumbnail/)).toBeTruthy()})
 it.each([401,403,409])('reports status %s independently',async status=>{vi.spyOn(compositionApi,'getApplication').mockRejectedValue(http(status)); renderPage(); await waitFor(()=>expect(screen.getByText(new RegExp(`application could not be restored \\(${status}\\)`))).toBeTruthy())})
 it('maps every backend validation location to a focusable editor',async()=>{const locations=['node:step-0','binding:0','parameter:0','output:0','port:step-0:input','asset:0'];const issues=locations.map((location,i)=>({code:`E${i}`,severity:'ERROR',objectType:'workflow',objectId:'wf',path:location,message:'bad',location}));vi.spyOn(compositionApi,'validateWorkflow').mockResolvedValue({ready:false,issues,snapshotId:'s'} as any);renderPage();await waitFor(()=>expect(screen.getByDisplayValue('Restored workflow')).toBeTruthy());fireEvent.click(screen.getByRole('button',{name:'Check publish readiness'}));for(const location of locations){const button=await screen.findByRole('button',{name:`Go to ${location}`});fireEvent.click(button);expect(document.activeElement?.getAttribute('data-editor-id')).toBe(location)}})
 it('maps entitlement issues and unknown locations without body focus',async()=>{const app={id:'app',version:'1.0',displayName:'App',description:'',input:{name:'MediaAsset',version:'1'},output:{name:'ImageAsset',version:'1'},requiredCapabilities:[],workflowIds:['wf'],requiredAssets:[],entitlements:['composition.create'],executionModes:['ASYNCHRONOUS'],lifecycle:'DRAFT',tenantId:'t',workspaceId:'w',revision:1};vi.spyOn(compositionApi,'getApplication').mockResolvedValue(app as any);vi.spyOn(compositionApi,'validateApplication').mockResolvedValue({ready:false,issues:[{code:'E',severity:'ERROR',objectType:'application',objectId:'app',path:'entitlements[0]',message:'bad',location:'entitlement:0'},{code:'U',severity:'ERROR',objectType:'workflow',objectId:'wf',path:'mystery',message:'unknown',location:'mystery'}],snapshotId:'s'} as any);renderPage();await waitFor(()=>expect(screen.getByText('Compose an Application')).toBeTruthy());fireEvent.click(screen.getAllByRole('checkbox')[1]);fireEvent.click(screen.getByRole('button',{name:'Check publish readiness'}));fireEvent.click(await screen.findByRole('button',{name:'Go to entitlement:0'}));expect(document.activeElement?.getAttribute('data-editor-id')).toBe('entitlement:0');fireEvent.click(await screen.findByRole('button',{name:'Go to mystery'}));expect(document.activeElement?.getAttribute('data-editor-id')).toBe('validation-fallback')})
})
