package com.example.platform.render.domain.workflow.planning;

public enum WorkflowDryRunIssueCode {
    MISSING_STEP,
    DUPLICATE_STEP_ID,
    UNKNOWN_DEPENDENCY,
    CYCLE_DETECTED,
    APPLY_TEMPLATE_MISSING_SPEC,
    UNSUPPORTED_STEP_TYPE,
    TEMPLATE_APPLICATION_NOT_VALIDATED,
    COMPOSITE_TEMPLATE_NOT_EXPANDED,
    EXECUTION_NOT_IMPLEMENTED,
    PROVIDER_SELECTION_NOT_ALLOWED,
    STORAGE_INTERNALS_NOT_ALLOWED
}
