package com.example.platform.render.domain.scenario;

/**
 * Issue codes for internal scenario validation.
 * Immutable enum. Internal domain model.
 */
public enum InternalScenarioIssueCode {
    SCENARIO_DEFINITION_INVALID,
    SCENARIO_INPUT_INVALID,
    TIMELINE_EDITING_FAILED,
    TIMELINE_VALIDATION_FAILED,
    VISUAL_CAPABILITY_VALIDATION_FAILED,
    EFFECT_PLAN_FAILED,
    EFFECT_PLAN_BLOCKED,
    TRANSITION_PLAN_FAILED,
    TRANSITION_PLAN_BLOCKED,
    BASIC_RENDER_PLAN_FAILED,
    BASIC_RENDER_PLAN_BLOCKED,
    OUTPUT_PROFILE_INVALID,
    EXPECTED_OUTCOME_MISMATCH,
    FORBIDDEN_EFFECT_NOT_BLOCKED,
    FORBIDDEN_TRANSITION_NOT_BLOCKED,
    RAW_FILTERGRAPH_EXPOSED,
    RAW_PROVIDER_COMMAND_EXPOSED,
    USER_RENDER_DAG_ALLOWED,
    PLUGIN_EXECUTION_NODE_ALLOWED,
    REMOTION_EXECUTION_ALLOWED,
    ARTIFACT_DAG_USED,
    FFMPEG_EXECUTION_ATTEMPTED,
    OPEN_CUE_CALL_ATTEMPTED,
    PRODUCT_RUNTIME_CALL_ATTEMPTED,
    STORAGE_RUNTIME_CALL_ATTEMPTED,
    PUBLIC_API_EXPOSED,
    PERSISTENCE_ATTEMPTED
}
