package com.example.platform.workerfabric.domain;

/** Typed Native Pull request rejection or reprobe reasons. */
public enum RequestWorkFailureReason {
    REQUEST_ID_REUSED_WITH_DIFFERENT_CONTEXT,
    WORKER_RUNTIME_NOT_REGISTERED,
    PHYSICAL_HOST_NOT_REGISTERED,
    REGISTRATION_STALE,
    WORKER_RUNTIME_UNHEALTHY,
    PHYSICAL_HOST_UNAVAILABLE,
    HOST_RESOURCE_SNAPSHOT_MISMATCH,
    STALE_HOST_RESOURCE_SNAPSHOT,
    HOST_INCARNATION_MISMATCH,
    RUNTIME_INCARNATION_MISMATCH,
    RESERVATION_RECONCILIATION_REQUIRED,
    UNKNOWN_RUNTIME_ELIGIBILITY,
    GRANT_CONFLICT
}
