package com.example.platform.workerfabric.domain;

/** Complete stable typed Stage-2 runtime/resource/hardware/dependency failure algebra. */
public enum RuntimeEligibilityReason {
    RUNTIME_SUPPORT_REQUIREMENT_MISSING(false),
    RUNTIME_SUPPORT_ADVERTISEMENT_MISSING(false),
    RUNTIME_SUPPORT_MISMATCH(false),
    RUNTIME_SUPPORT_UNSUPPORTED(false),
    PROBE_UNKNOWN(true),
    PROBE_STALE(false),
    PROBE_FAILED(false),
    NO_ELIGIBLE_WORKER(false),
    NO_ELIGIBLE_DEVICE(false),
    WORKER_UNAVAILABLE(false),
    HOST_UNAVAILABLE(false),
    DEVICE_UNAVAILABLE(false),
    RUNTIME_UNAVAILABLE(false),
    SANDBOX_RUNTIME_UNAVAILABLE(false),
    INSUFFICIENT_CURRENT_RESOURCE(false),
    STALE_HOST_RESOURCE_SNAPSHOT(false),
    HOST_INCARNATION_MISMATCH(false),
    RUNTIME_INCARNATION_MISMATCH(false),
    RESERVATION_CONFLICT(false),
    UNKNOWN_RUNTIME_ELIGIBILITY(true),
    PROVIDER_HARDWARE_INCOMPLETE_CRITICAL_EVIDENCE(true),
    PROVIDER_HARDWARE_PROVIDER_IMPLEMENTATION_MISMATCH(false),
    PROVIDER_HARDWARE_WORKER_RUNTIME_MISMATCH(false),
    PROVIDER_HARDWARE_PHYSICAL_HOST_MISMATCH(false),
    PROVIDER_HARDWARE_DEVICE_IDENTITY_MISMATCH(false),
    PROVIDER_HARDWARE_STALE_OBSERVATION(true),
    PROVIDER_HARDWARE_PROBE_UNKNOWN(true),
    PROVIDER_HARDWARE_PROBE_FAILED(true),
    PROVIDER_HARDWARE_RUNTIME_UNAVAILABLE(false),
    PROVIDER_HARDWARE_CPU_ARCHITECTURE_INCOMPATIBLE(false),
    PROVIDER_HARDWARE_DEVICE_CLASS_UNAVAILABLE(false),
    PROVIDER_HARDWARE_DEVICE_UNAVAILABLE(false),
    PROVIDER_HARDWARE_DRIVER_RUNTIME_INCOMPATIBLE(false),
    PROVIDER_HARDWARE_PROVIDER_BUILD_FEATURE_MISSING(false),
    PROVIDER_HARDWARE_CODEC_OR_FILTER_FEATURE_MISSING(false),
    PROVIDER_HARDWARE_DEVICE_FEATURE_UNAVAILABLE(false),
    PROVIDER_HARDWARE_DEVICE_NOT_EXPOSED(false),
    PROVIDER_HARDWARE_SANDBOX_PERMISSION_UNAVAILABLE(false),
    RUNTIME_DEPENDENCY_INCOMPLETE_CRITICAL_EVIDENCE(true),
    RUNTIME_DEPENDENCY_PROBE_SCHEMA_MISMATCH(true),
    RUNTIME_DEPENDENCY_PROVIDER_IMPLEMENTATION_MISMATCH(false),
    RUNTIME_DEPENDENCY_WORKER_RUNTIME_MISMATCH(false),
    RUNTIME_DEPENDENCY_DEVICE_BINDING_MISMATCH(false),
    RUNTIME_DEPENDENCY_STALE_OBSERVATION(true),
    RUNTIME_DEPENDENCY_MISSING(false),
    RUNTIME_DEPENDENCY_VERSION_INCOMPATIBLE(false),
    RUNTIME_DEPENDENCY_ABI_INCOMPATIBLE(false),
    RUNTIME_DEPENDENCY_FEATURE_MISSING(false),
    RUNTIME_DEPENDENCY_BUILD_RUNTIME_FLAG_MISSING(false);

    private final boolean unknownEvidence;

    RuntimeEligibilityReason(boolean unknownEvidence) {
        this.unknownEvidence = unknownEvidence;
    }

    public boolean unknownEvidence() {
        return unknownEvidence;
    }
}
