package com.example.platform.workerfabric.domain;

/** Complete typed mutable-runtime failure algebra for Epoch 3 Task B. */
public enum RuntimeEligibilityReason {
    PROBE_UNKNOWN,
    PROBE_STALE,
    PROBE_FAILED,
    NO_ELIGIBLE_WORKER,
    NO_ELIGIBLE_DEVICE,
    WORKER_UNAVAILABLE,
    HOST_UNAVAILABLE,
    DEVICE_UNAVAILABLE,
    RUNTIME_UNAVAILABLE,
    SANDBOX_RUNTIME_UNAVAILABLE,
    INSUFFICIENT_CURRENT_RESOURCE,
    STALE_HOST_RESOURCE_SNAPSHOT,
    HOST_INCARNATION_MISMATCH,
    RUNTIME_INCARNATION_MISMATCH,
    RESERVATION_CONFLICT,
    UNKNOWN_RUNTIME_ELIGIBILITY
}
