package com.example.platform.render.domain.timeline.diff;

public enum TimelineConflictType {
    TRACK_ORDER_CONFLICT,
    CLIP_TIMING_CONFLICT,
    CLIP_OVERLAP_CONFLICT,
    ASSET_BINDING_CONFLICT,
    CAPTION_TEXT_CONFLICT,
    TEXT_STYLE_CONFLICT,
    WATERMARK_POSITION_CONFLICT,
    TEMPLATE_PARAMETER_CONFLICT,
    COMPOSITE_TEMPLATE_CHILD_CONFLICT,
    WORKFLOW_STEP_CONFLICT,
    OUTPUT_PROFILE_CONFLICT,
    RENDER_IMPACT_CONFLICT,
    UNKNOWN_CONFLICT
}
