-- ============================================================
-- 1. CORE INFRASTRUCTURE
-- ============================================================
-- render_job, outbox_events, audit_records, schedules, config_item,
-- storage_object, cloud_resource_definition, secret_ref, app_datasource,
-- quota_definitions, notification_event, notification_template,
-- notification_delivery, notification_record

create table render_job (
    id varchar(64) primary key,
    project_id varchar(128) not null,
    timeline_snapshot_id varchar(128) not null,
    profile varchar(128) not null,
    status varchar(32) not null,
    created_at timestamp not null,
    ai_script text,
    artifact_uri text,
    error_message text,
    tenant_id varchar(64),
    pipeline_plan_json text,
    pipeline_execution_json text,
    base_job_id varchar(64)
);

create index ix_render_job_project_id on render_job(project_id);
create index ix_render_job_status on render_job(status);
create index ix_render_job_base_job_id on render_job(base_job_id);

create table outbox_events (
    id varchar(64) primary key,
    aggregate_type varchar(100) not null,
    aggregate_id varchar(100) not null,
    event_type varchar(150) not null,
    event_version int not null,
    payload text not null,
    status varchar(50) not null,
    created_at timestamp not null,
    published_at timestamp,
    retry_count int not null default 0,
    next_attempt_at timestamp,
    idempotency_key varchar(255)
);

create index ix_outbox_events_status_created_at on outbox_events(status, created_at);
create index ix_outbox_events_aggregate on outbox_events(aggregate_type, aggregate_id);
create index ix_outbox_events_idempotency_key on outbox_events(idempotency_key);
create index ix_outbox_events_next_attempt_at on outbox_events(next_attempt_at);

create table audit_records (
    id varchar(64) primary key,
    actor_type varchar(50) not null,
    actor_id varchar(100),
    action varchar(120) not null,
    resource_type varchar(120) not null,
    resource_id varchar(120),
    payload text,
    created_at timestamp not null,
    category varchar(50)
);

create index ix_audit_records_created_at on audit_records(created_at);
create index ix_audit_records_actor_id on audit_records(actor_id);
create index ix_audit_records_resource on audit_records(resource_type, resource_id);

create table schedules (
    id varchar(64) primary key,
    schedule_code varchar(100) not null,
    handler_code varchar(120) not null,
    enabled boolean not null,
    created_at timestamp not null
);

create index ix_schedules_schedule_code on schedules(schedule_code);

create table config_item (
    id bigint generated by default as identity primary key,
    namespace_key varchar(128) not null,
    config_key varchar(128) not null,
    value_json text not null,
    value_version int not null,
    updated_at timestamp not null,
    unique(namespace_key, config_key, value_version)
);

create index ix_config_item_namespace_key on config_item(namespace_key);

create table storage_object (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    bucket varchar(128) not null,
    object_key text not null,
    content_type varchar(255),
    checksum_sha256 varchar(128),
    file_size_bytes bigint,
    lifecycle_policy varchar(64),
    created_at timestamp not null
);

create index ix_storage_object_provider_code on storage_object(provider_code);
create index ix_storage_object_bucket on storage_object(bucket);

create table cloud_resource_definition (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    resource_type varchar(64) not null,
    logical_name varchar(128) not null,
    spec_json text not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table secret_ref (
    id varchar(64) primary key,
    namespace_key varchar(128) not null,
    secret_key varchar(128) not null,
    backend_type varchar(64) not null,
    backend_ref varchar(255) not null,
    created_at timestamp not null,
    unique(namespace_key, secret_key)
);

create table app_datasource (
    id varchar(64) primary key,
    datasource_code varchar(64) not null unique,
    datasource_kind varchar(32) not null,
    dialect varchar(32),
    jdbc_url text,
    secret_ref varchar(255),
    is_primary boolean not null,
    usage_role varchar(64) not null,
    created_at timestamp not null
);

create table quota_definitions (
    id varchar(64) primary key,
    quota_code varchar(80) not null,
    unit varchar(50) not null,
    created_at timestamp not null
);

create table notification_event (
    id varchar(64) primary key,
    event_type varchar(128) not null,
    subject_id varchar(128),
    payload text not null,
    created_at timestamp not null
);

create index ix_notification_event_event_type on notification_event(event_type);
create index ix_notification_event_created_at on notification_event(created_at);

create table notification_template (
    id bigint generated by default as identity primary key,
    template_code varchar(64) not null,
    channel varchar(32) not null,
    locale varchar(16) not null,
    version int not null,
    subject_template varchar(255),
    body_template text not null,
    unique(template_code, channel, locale, version)
);

create table notification_delivery (
    id varchar(64) primary key,
    event_id varchar(64) not null,
    channel varchar(32) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    request_payload text,
    response_payload text,
    attempt_count int not null,
    created_at timestamp not null
);

create index ix_notification_delivery_event_id on notification_delivery(event_id);
create index ix_notification_delivery_status on notification_delivery(status);

create table notification_record (
    id varchar(64) primary key,
    event_id varchar(64) not null,
    channel varchar(32) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    subject varchar(512),
    body text,
    metadata_json text,
    attempt_count int not null default 1,
    created_at timestamp not null
);

create index ix_notification_record_event_id on notification_record(event_id);
create index ix_notification_record_status on notification_record(status);


-- ============================================================
-- 2. IDENTITY & ACCESS
-- ============================================================
-- tenant, project, "user", api_key, workspace, workspace_member,
-- workspace_group, workspace_group_member, role, permission,
-- role_permission, user_role_assignment, group_role_assignment,
-- service_account, api_client

create table tenant (
    id varchar(64) primary key,
    name varchar(255) not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create table project (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    name varchar(255) not null,
    description text,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create index ix_project_tenant_id on project(tenant_id);

create table "user" (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    username varchar(128) not null,
    email varchar(255) not null,
    role varchar(32) not null default 'MEMBER',
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create index ix_user_tenant_id on "user"(tenant_id);

create table api_key (
    id varchar(64) primary key,
    tenant_id varchar(64),
    fingerprint varchar(32) not null,
    hashed_key varchar(128) not null unique,
    principal varchar(255) not null,
    created_at timestamp not null,
    last_used_at timestamp,
    revoked_at timestamp
);

create index ix_api_key_fingerprint on api_key(fingerprint);

create table workspace (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    name varchar(255) not null,
    description text,
    plan_tier varchar(64) not null default 'FREE',
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_workspace_tenant_id on workspace(tenant_id);

create table workspace_member (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    user_id varchar(64) not null,
    role varchar(64) not null,
    status varchar(32) not null default 'ACTIVE',
    joined_at timestamp not null,
    updated_at timestamp not null
);

create index ix_workspace_member_workspace_id on workspace_member(workspace_id);
create index ix_workspace_member_user_id on workspace_member(user_id);

create table workspace_group (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    name varchar(255) not null,
    description text,
    created_at timestamp not null
);

create index ix_workspace_group_workspace_id on workspace_group(workspace_id);

create table workspace_group_member (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    group_id varchar(64) not null,
    member_id varchar(64) not null,
    created_at timestamp not null
);

create index ix_workspace_group_member_group_id on workspace_group_member(group_id);
create index ix_workspace_group_member_member_id on workspace_group_member(member_id);

create table role (
    id varchar(64) primary key,
    role_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    scope varchar(32) not null,
    created_at timestamp not null
);

create table permission (
    id varchar(64) primary key,
    permission_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    resource_type varchar(128),
    created_at timestamp not null
);

create table role_permission (
    id varchar(64) primary key,
    role_id varchar(64) not null,
    permission_id varchar(64) not null,
    created_at timestamp not null
);

create index ix_role_permission_role_id on role_permission(role_id);

create table user_role_assignment (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64) not null,
    role_id varchar(64) not null,
    assigned_by varchar(64),
    created_at timestamp not null
);

create index ix_user_role_assignment_user_id on user_role_assignment(user_id);
create index ix_user_role_assignment_workspace_id on user_role_assignment(workspace_id);

create table group_role_assignment (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    group_id varchar(64) not null,
    role_id varchar(64) not null,
    assigned_at timestamp not null
);

create index ix_group_role_assignment_group_id on group_role_assignment(group_id);

create table service_account (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64) not null,
    name varchar(255) not null,
    description text,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create index ix_service_account_workspace_id on service_account(workspace_id);

create table api_client (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64) not null,
    name varchar(255) not null,
    client_key_hash varchar(255) not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null
);

create index ix_api_client_workspace_id on api_client(workspace_id);


-- ============================================================
-- 3. MEDIA & RENDERING
-- ============================================================
-- artifact, artifact_relation, render_job_status_history,
-- timeline_snapshot, timeline_revision, effect_pack, effect_pack_effect,
-- client_export_session, media_asset_metadata

create table artifact (
    id varchar(64) primary key,
    render_job_id varchar(64) not null,
    project_id varchar(64) not null,
    storage_uri text not null,
    format varchar(32),
    resolution varchar(32),
    duration bigint,
    created_at timestamp not null,
    status varchar(32) not null default 'ACTIVE',
    tombstoned_at timestamp
);

create index ix_artifact_render_job_id on artifact(render_job_id);
create index ix_artifact_project_id on artifact(project_id);
create index ix_artifact_status on artifact(status);

create table artifact_relation (
    id varchar(64) primary key,
    source_artifact_id varchar(64) not null,
    target_artifact_id varchar(64) not null,
    relation_type varchar(64) not null,
    created_at timestamp not null,
    constraint fk_artifact_relation_source foreign key (source_artifact_id) references artifact(id) on delete restrict,
    constraint fk_artifact_relation_target foreign key (target_artifact_id) references artifact(id) on delete restrict
);

create index ix_artifact_relation_source on artifact_relation(source_artifact_id);
create index ix_artifact_relation_target on artifact_relation(target_artifact_id);

create table render_job_status_history (
    id varchar(64) primary key,
    job_id varchar(64) not null,
    from_status varchar(30),
    to_status varchar(30) not null,
    reason varchar(255),
    error_code varchar(100),
    occurred_at timestamp not null default now()
);

create index ix_rjsh_job_id on render_job_status_history(job_id);

create table timeline_snapshot (
    id varchar(64) primary key,
    project_id varchar(64) not null,
    tenant_id varchar(64),
    payload_json text not null,
    schema_version varchar(32) default '2.0.0',
    created_at timestamp not null default CURRENT_TIMESTAMP,
    content_hash varchar(64),
    revision_number int
);

create index idx_timeline_snapshot_project on timeline_snapshot(project_id);

create table timeline_revision (
    id varchar(64) primary key,
    project_id varchar(64) not null,
    tenant_id varchar(64),
    parent_revision_id varchar(64),
    revision_number int not null,
    snapshot_id varchar(64) not null,
    internal_revision int not null default 0,
    content_hash varchar(64) not null,
    schema_version varchar(32) not null default 'internal-1.0',
    source varchar(32) not null,
    author_user_id varchar(64),
    edit_session_id varchar(64),
    message varchar(512),
    change_summary_json text,
    created_at timestamp not null,
    patch_ops_json text,
    labels_json varchar(512)
);

create unique index ux_timeline_revision_project_num on timeline_revision(project_id, revision_number);
create index ix_timeline_revision_project_created on timeline_revision(project_id, created_at desc);
create index ix_timeline_revision_parent on timeline_revision(parent_revision_id);
create index ix_timeline_revision_snapshot on timeline_revision(snapshot_id);
create index ix_timeline_revision_edit_session on timeline_revision(project_id, edit_session_id, created_at desc);
create index ix_timeline_revision_project_source on timeline_revision(project_id, source);

create table effect_pack (
    id varchar(64) primary key,
    pack_id varchar(128) not null,
    version varchar(32) not null,
    name varchar(255) not null,
    description varchar(1024),
    author varchar(128),
    compatibility varchar(32) default '2.0',
    allowed_tiers text,
    tenant_id varchar(64) not null default '',
    builtin boolean not null default false,
    created_at timestamp not null default CURRENT_TIMESTAMP,
    updated_at timestamp not null default CURRENT_TIMESTAMP
);

create unique index uq_effect_pack_identity on effect_pack(pack_id, version, tenant_id);
create index idx_effect_pack_tenant on effect_pack(tenant_id);

create table effect_pack_effect (
    id varchar(64) primary key,
    pack_row_id varchar(64) not null,
    effect_key varchar(128) not null,
    display_name varchar(255) not null,
    category varchar(64) not null,
    description varchar(1024),
    parameter_schema text,
    default_values text,
    provider_mappings text,
    allowed_tiers text,
    sort_order int not null default 0,
    constraint fk_effect_pack_effect_pack foreign key (pack_row_id) references effect_pack(id)
);

create unique index uq_effect_pack_effect_key on effect_pack_effect(pack_row_id, effect_key);

create table client_export_session (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    workspace_id varchar(64),
    project_id varchar(64) not null,
    user_id varchar(128),
    timeline_snapshot_id varchar(64),
    export_type varchar(32) not null default 'CLIENT_BROWSER',
    preset varchar(64),
    status varchar(32) not null default 'CREATED',
    progress int not null default 0,
    resolution varchar(32) default '1280x720',
    fps int default 30,
    format varchar(16) default 'webm',
    watermark_enabled boolean default true,
    video_bitrate int,
    audio_bitrate int,
    max_duration_sec int,
    output_uri varchar(512),
    artifact_id varchar(64),
    download_path varchar(512),
    error_code varchar(64),
    error_message varchar(1024),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    expires_at timestamp
);

create index ix_cex_tenant on client_export_session(tenant_id);
create index ix_cex_project on client_export_session(project_id);
create index ix_cex_status on client_export_session(status);
create index ix_cex_tenant_proj on client_export_session(tenant_id, project_id);

create table media_asset_metadata (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    project_id varchar(64) not null,
    asset_id varchar(64) not null,
    asset_uri varchar(1024) not null,
    valid boolean not null default false,
    container varchar(32),
    file_size_bytes bigint default 0,
    duration_ms double default 0,
    width int default 0,
    height int default 0,
    fps double default 0,
    video_codec varchar(64),
    audio_codec varchar(64),
    audio_sample_rate int default 0,
    audio_channels int default 0,
    has_audio boolean default false,
    rotation int default 0,
    color_space varchar(32),
    bitrate bigint default 0,
    is_vfr boolean default false,
    stream_count int default 0,
    client_export_compatible boolean default false,
    normalize_required boolean default true,
    warnings varchar(4096),
    error_message varchar(1024),
    probed_at timestamp not null default current_timestamp
);

create index ix_mam_tenant_asset on media_asset_metadata(tenant_id, asset_id);
create index ix_mam_project on media_asset_metadata(project_id);
create index ix_mam_probed_at on media_asset_metadata(probed_at);


-- ============================================================
-- 4. COMMERCE & BILLING
-- ============================================================
-- commerce_product, commerce_price, provider_product_mapping,
-- checkout_session, purchase_order, payment_attempt,
-- provider_webhook_event, subscription_contract, subscription_plan,
-- billing_invoice, billing_ledger_entry, credit_wallet,
-- credit_transaction, invoice_line_item, pricing_rule, usage_meter,
-- usage_record, rated_usage_record, custom_pricing_rule,
-- discount_policy, commerce_cart, commerce_cart_line

create table commerce_product (
    id varchar(64) primary key,
    product_code varchar(128) not null unique,
    purchase_mode varchar(64) not null,
    feature_bundle_code varchar(128) not null,
    quota_profile_code varchar(128),
    status varchar(32) not null,
    created_at timestamp not null
);

create table commerce_price (
    id varchar(64) primary key,
    product_id varchar(64) not null,
    price_code varchar(128) not null unique,
    currency_code varchar(8) not null,
    amount_minor bigint not null,
    billing_interval varchar(32),
    created_at timestamp not null
);

create index ix_commerce_price_product_id on commerce_price(product_id);

create table provider_product_mapping (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    external_product_ref varchar(255) not null,
    external_price_ref varchar(255),
    product_id varchar(64) not null,
    created_at timestamp not null
);

create index ix_provider_product_mapping_product_id on provider_product_mapping(product_id);

create table checkout_session (
    id varchar(64) primary key,
    checkout_session_code varchar(128) not null unique,
    product_id varchar(64) not null,
    provider_code varchar(64),
    session_status varchar(32) not null,
    success_url text,
    cancel_url text,
    created_at timestamp not null,
    tenant_id varchar(64),
    user_id varchar(128),
    cart_id varchar(64)
);

create index ix_checkout_session_product_id on checkout_session(product_id);
create index ix_checkout_session_tenant on checkout_session(tenant_id);

create table purchase_order (
    id varchar(64) primary key,
    checkout_session_id varchar(64),
    canonical_product_code varchar(128) not null,
    order_status varchar(32) not null,
    total_amount_minor bigint,
    currency_code varchar(8),
    created_at timestamp not null,
    tenant_id varchar(64)
);

create index ix_purchase_order_checkout_session_id on purchase_order(checkout_session_id);
create index ix_purchase_order_tenant on purchase_order(tenant_id);

create table payment_attempt (
    id varchar(64) primary key,
    purchase_order_id varchar(64),
    provider_code varchar(64) not null,
    provider_reference varchar(255),
    attempt_status varchar(32) not null,
    amount_minor bigint,
    currency_code varchar(8),
    request_payload text,
    response_payload text,
    created_at timestamp not null
);

create index ix_payment_attempt_purchase_order_id on payment_attempt(purchase_order_id);

create table provider_webhook_event (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    webhook_event_key varchar(255) not null unique,
    webhook_event_type varchar(128) not null,
    webhook_event_version int not null,
    signature_valid boolean not null,
    payload text not null,
    created_at timestamp not null
);

create table subscription_contract (
    id varchar(64) primary key,
    subject_type varchar(32) not null,
    subject_id varchar(128) not null,
    canonical_product_code varchar(128) not null,
    provider_code varchar(64),
    external_contract_ref varchar(255),
    contract_state varchar(32) not null,
    period_start_at timestamp,
    period_end_at timestamp,
    created_at timestamp not null,
    plan_key varchar(128),
    included_quota_used text,
    tenant_id varchar(64)
);

create index ix_subscription_contract_subject on subscription_contract(subject_type, subject_id);
create index ix_subscription_contract_tenant on subscription_contract(tenant_id);

create table subscription_plan (
    id varchar(64) primary key,
    plan_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    billing_interval varchar(32) not null,
    base_price_minor bigint not null,
    currency_code varchar(8) not null,
    included_quota text,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index ix_subscription_plan_key on subscription_plan(plan_key);
create index ix_subscription_plan_status on subscription_plan(status);

create table billing_invoice (
    id varchar(64) primary key,
    contract_id varchar(64),
    provider_code varchar(64),
    external_invoice_ref varchar(255),
    invoice_status varchar(32) not null,
    amount_due_minor bigint,
    amount_paid_minor bigint,
    currency_code varchar(8),
    created_at timestamp not null
);

create index ix_billing_invoice_contract_id on billing_invoice(contract_id);

create table billing_ledger_entry (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64),
    entry_type varchar(32) not null,
    amount_minor bigint not null,
    currency_code varchar(8) not null,
    reference_type varchar(64),
    reference_id varchar(64),
    description text,
    created_at timestamp not null default now()
);

create index ix_billing_ledger_tenant on billing_ledger_entry(tenant_id);
create index ix_billing_ledger_type on billing_ledger_entry(entry_type);
create index ix_billing_ledger_ref on billing_ledger_entry(reference_type, reference_id);
create index ix_billing_ledger_created on billing_ledger_entry(created_at);

create table credit_wallet (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64),
    balance_minor bigint not null default 0,
    currency_code varchar(8) not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index ix_credit_wallet_tenant on credit_wallet(tenant_id);
create index ix_credit_wallet_status on credit_wallet(status);

create table credit_transaction (
    id varchar(64) primary key,
    wallet_id varchar(64) not null,
    transaction_type varchar(32) not null,
    amount_minor bigint not null,
    balance_after_minor bigint not null,
    reference_type varchar(64),
    reference_id varchar(64),
    description text,
    created_at timestamp not null default now()
);

create index ix_credit_txn_wallet on credit_transaction(wallet_id);
create index ix_credit_txn_type on credit_transaction(transaction_type);
create index ix_credit_txn_created on credit_transaction(created_at);

create table invoice_line_item (
    id varchar(64) primary key,
    invoice_id varchar(64) not null,
    line_type varchar(32) not null,
    description text,
    quantity double precision,
    unit_price_minor bigint,
    amount_minor bigint not null,
    currency_code varchar(8) not null,
    period_start timestamp,
    period_end timestamp,
    created_at timestamp not null default now()
);

create index ix_invoice_line_item_invoice on invoice_line_item(invoice_id);

create table pricing_rule (
    id varchar(64) primary key,
    rule_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    pricing_model varchar(32) not null,
    meter_key varchar(128),
    unit_price_minor bigint,
    currency_code varchar(8),
    tier_config text,
    status varchar(32) not null default 'ACTIVE',
    effective_from timestamp,
    effective_to timestamp,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index ix_pricing_rule_key on pricing_rule(rule_key);
create index ix_pricing_rule_model on pricing_rule(pricing_model);
create index ix_pricing_rule_status on pricing_rule(status);

create table usage_meter (
    id varchar(64) primary key,
    meter_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    unit varchar(64) not null,
    aggregation_type varchar(32) not null,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null default now()
);

create index ix_usage_meter_key on usage_meter(meter_key);

create table usage_record (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64),
    meter_key varchar(128) not null,
    quantity double precision not null,
    unit varchar(64) not null,
    recorded_at timestamp not null,
    idempotency_key varchar(255) unique,
    created_at timestamp not null default now()
);

create index ix_usage_record_tenant on usage_record(tenant_id);
create index ix_usage_record_meter on usage_record(meter_key);
create index ix_usage_record_recorded on usage_record(recorded_at);

create table rated_usage_record (
    id varchar(64) primary key,
    usage_record_id varchar(64) not null,
    pricing_rule_id varchar(64) not null,
    rated_amount_minor bigint not null,
    currency_code varchar(8) not null,
    rating_details text,
    created_at timestamp not null default now()
);

create index ix_rated_usage_record_usage on rated_usage_record(usage_record_id);
create index ix_rated_usage_record_rule on rated_usage_record(pricing_rule_id);

create table custom_pricing_rule (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    meter_key varchar(128) not null,
    override_price_minor bigint,
    discount_percent double precision,
    effective_from timestamp,
    effective_to timestamp,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null default now()
);

create index ix_custom_pricing_tenant on custom_pricing_rule(tenant_id);
create index ix_custom_pricing_meter on custom_pricing_rule(meter_key);

create table discount_policy (
    id varchar(64) primary key,
    policy_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    discount_type varchar(32) not null,
    discount_value double precision not null,
    conditions text,
    status varchar(32) not null default 'ACTIVE',
    effective_from timestamp,
    effective_to timestamp,
    created_at timestamp not null default now()
);

create index ix_discount_policy_key on discount_policy(policy_key);
create index ix_discount_policy_status on discount_policy(status);

create table commerce_cart (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    user_id varchar(128),
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_commerce_cart_tenant on commerce_cart(tenant_id);

create table commerce_cart_line (
    id varchar(64) primary key,
    cart_id varchar(64) not null,
    product_code varchar(128) not null,
    quantity int not null,
    created_at timestamp not null,
    unique(cart_id, product_code)
);

create index ix_commerce_cart_line_cart on commerce_cart_line(cart_id);


-- ============================================================
-- 5. ENTITLEMENT & QUOTA
-- ============================================================
-- feature_definition, feature_bundle, feature_bundle_item,
-- entitlement_grant, entitlement_override, entitlement_bundle,
-- quota_profile, quota_usage, workspace_entitlement_pool,
-- workspace_member_entitlement_grant, workspace_quota_allocation,
-- tenant_entitlement_tier

create table feature_definition (
    id varchar(64) primary key,
    feature_code varchar(128) not null unique,
    description varchar(255),
    created_at timestamp not null
);

create table feature_bundle (
    id varchar(64) primary key,
    bundle_code varchar(128) not null unique,
    description varchar(255),
    created_at timestamp not null
);

create table feature_bundle_item (
    id varchar(64) primary key,
    bundle_id varchar(64) not null,
    feature_id varchar(64) not null,
    created_at timestamp not null
);

create index ix_feature_bundle_item_bundle_id on feature_bundle_item(bundle_id);
create index ix_feature_bundle_item_feature_id on feature_bundle_item(feature_id);

create table entitlement_grant (
    id varchar(64) primary key,
    subject_type varchar(32) not null,
    subject_id varchar(128) not null,
    bundle_code varchar(128) not null,
    quota_profile_code varchar(128),
    source_type varchar(32) not null,
    source_ref varchar(255),
    grant_status varchar(32) not null,
    effective_at timestamp not null,
    expires_at timestamp
);

create index ix_entitlement_grant_subject on entitlement_grant(subject_type, subject_id);

create table entitlement_override (
    id varchar(64) primary key,
    subject_type varchar(32) not null,
    subject_id varchar(128) not null,
    override_kind varchar(64) not null,
    override_payload text not null,
    effective_at timestamp not null,
    expires_at timestamp,
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp,
    updated_at timestamp
);

create index ix_entitlement_override_subject on entitlement_override(subject_type, subject_id);

create table entitlement_bundle (
    id varchar(64) primary key,
    bundle_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    status varchar(32) not null default 'ACTIVE',
    allowed_providers json,
    allowed_presets json,
    gpu_allowed boolean not null default false,
    remote_worker_allowed boolean not null default false,
    custom_fonts_allowed boolean not null default false,
    max_subtitle_tracks int not null default 2,
    max_concurrent_jobs int not null default 1,
    monthly_render_minutes bigint not null default 60,
    storage_limit_bytes bigint not null default 1073741824,
    watermark_required boolean not null default true,
    priority_queue_allowed boolean not null default false,
    beta_effects_allowed boolean not null default false,
    prompt_execution_limit bigint not null default 100,
    extension_execution_allowed boolean not null default false,
    api_access_allowed boolean not null default false,
    mcp_access_allowed boolean not null default false,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_entitlement_bundle_bundle_key on entitlement_bundle(bundle_key);
create index ix_entitlement_bundle_status on entitlement_bundle(status);

create table quota_profile (
    id varchar(64) primary key,
    profile_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    monthly_render_minutes bigint not null default 60,
    daily_render_jobs int not null default 5,
    concurrent_render_jobs int not null default 1,
    storage_bytes bigint not null default 1073741824,
    gpu_minutes bigint not null default 0,
    remote_worker_jobs int not null default 0,
    prompt_executions bigint not null default 100,
    extension_executions bigint not null default 0,
    api_calls_per_minute int not null default 60,
    mcp_calls_per_minute int not null default 30,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_quota_profile_profile_key on quota_profile(profile_key);

create table quota_usage (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    feature_code varchar(80) not null,
    usage_value int not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_quota_usage_tenant_id on quota_usage(tenant_id);
create index ix_quota_usage_tenant_feature on quota_usage(tenant_id, feature_code);

create table workspace_entitlement_pool (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    feature_key varchar(128) not null,
    total_quota bigint not null default 0,
    used_quota bigint not null default 0,
    period varchar(32) not null default 'MONTHLY',
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_workspace_entitlement_pool_workspace_id on workspace_entitlement_pool(workspace_id);
create index ix_workspace_entitlement_pool_feature_key on workspace_entitlement_pool(feature_key);

create table workspace_member_entitlement_grant (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    member_id varchar(64) not null,
    feature_key varchar(128) not null,
    quota_amount bigint not null default 0,
    starts_at timestamp not null,
    expires_at timestamp,
    status varchar(32) not null default 'ACTIVE',
    granted_by varchar(64),
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_workspace_member_grant_workspace_id on workspace_member_entitlement_grant(workspace_id);
create index ix_workspace_member_grant_member_id on workspace_member_entitlement_grant(member_id);
create index ix_workspace_member_grant_status on workspace_member_entitlement_grant(status);

create table workspace_quota_allocation (
    id varchar(64) primary key,
    workspace_id varchar(64) not null,
    member_id varchar(64) not null,
    quota_profile_key varchar(128) not null,
    allocated_amount bigint not null default 0,
    used_amount bigint not null default 0,
    period varchar(32) not null default 'MONTHLY',
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_workspace_quota_alloc_workspace_id on workspace_quota_allocation(workspace_id);
create index ix_workspace_quota_alloc_member_id on workspace_quota_allocation(member_id);

create table tenant_entitlement_tier (
    tenant_id varchar(64) not null primary key,
    tier varchar(32) not null default 'FREE',
    updated_at timestamp not null default now()
);

create index ix_tenant_entitlement_tier_tier on tenant_entitlement_tier(tier);


-- ============================================================
-- 6. PLATFORM CAPABILITIES
-- ============================================================
-- prompt_template, prompt_template_version, prompt_execution_run,
-- prompt_evaluation_result, extension_definition, extension_invocation,
-- extension_routing_rule, extension_resource_limit,
-- extension_rollback_point, extension_audit_event, sandbox_execution_job,
-- problematic_data_record, quarantined_render_jobs,
-- quarantined_prompt_executions, quarantined_provider_workers,
-- problematic_data_rule_config, nlq_report_definition,
-- nlq_query_history, nlq_report_execution

create table prompt_template (
    template_id varchar(64) primary key,
    name varchar(255) not null,
    description text,
    category varchar(128),
    tags text,
    owner varchar(128),
    status varchar(32) not null default 'DRAFT',
    schema_version varchar(32) not null default '1.0.0',
    current_prompt_version varchar(32),
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index idx_prompt_template_status on prompt_template(status);

create table prompt_template_version (
    version_id varchar(64) primary key,
    template_id varchar(64) not null references prompt_template(template_id),
    prompt_version varchar(32) not null,
    template_body text not null,
    variable_schema_json text,
    changelog text,
    created_by varchar(128),
    created_at timestamp not null default now(),
    checksum varchar(64),
    previous_version varchar(32),
    deprecated boolean not null default false,
    unique(template_id, prompt_version)
);

create index idx_prompt_version_template on prompt_template_version(template_id);

create table prompt_execution_run (
    execution_id varchar(64) primary key,
    template_id varchar(64) not null references prompt_template(template_id),
    prompt_version varchar(32) not null,
    tenant_id varchar(64) not null,
    user_id varchar(128) not null,
    model_provider varchar(64),
    model_name varchar(64),
    rendered_prompt_hash varchar(64),
    redacted_prompt_preview varchar(512),
    input_variables_redacted_json text,
    output_summary text,
    status varchar(32) not null default 'PENDING',
    risk_level varchar(32) not null default 'LOW',
    token_estimate int not null default 0,
    cost_estimate double precision not null default 0,
    started_at timestamp not null default now(),
    finished_at timestamp,
    error_code varchar(64),
    error_details_json text,
    related_prompt_file varchar(256),
    related_manifest_entry varchar(256)
);

create index idx_prompt_execution_template on prompt_execution_run(template_id);
create index idx_prompt_execution_tenant on prompt_execution_run(tenant_id);
create index idx_prompt_execution_status on prompt_execution_run(status);

create table prompt_evaluation_result (
    evaluation_id varchar(64) primary key,
    execution_id varchar(64) not null references prompt_execution_run(execution_id),
    template_id varchar(64) not null,
    evaluator_user_id varchar(128) not null,
    acceptance_criteria_met boolean not null default false,
    documentation_updated boolean not null default false,
    manifest_updated boolean not null default false,
    tests_pass boolean not null default false,
    has_high_risk_changes boolean not null default false,
    has_human_review_items boolean not null default false,
    has_scope_creep boolean not null default false,
    has_false_claims boolean not null default false,
    overall_verdict varchar(32) not null,
    evaluated_at timestamp not null default now()
);

create table extension_definition (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_type varchar(64) not null,
    language varchar(32),
    runtime varchar(64),
    version varchar(64) not null,
    artifact_uri text,
    status varchar(32) not null,
    timeout_ms bigint,
    config_schema text,
    created_at timestamp not null,
    trust_level varchar(32) not null default 'SEMI_TRUSTED',
    sandboxed boolean not null default true,
    max_concurrency int not null default 4,
    max_memory_mb int not null default 256,
    max_cpu_percent int not null default 50,
    max_queue_size int not null default 100,
    max_input_bytes bigint not null default 10485760,
    max_output_bytes bigint not null default 4194304,
    requires_review boolean not null default false,
    review_status varchar(32) default 'APPROVED',
    unique(extension_code, version)
);

create table extension_invocation (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_version varchar(64) not null,
    caller_module varchar(128) not null,
    input_summary text,
    output_summary text,
    exit_status varchar(32),
    duration_ms bigint,
    created_at timestamp not null,
    trace_id varchar(128),
    trust_level varchar(32),
    input_bytes bigint,
    output_bytes bigint,
    cpu_time_ms bigint,
    memory_peak_mb bigint,
    routing_rule_id varchar(64)
);

create index ix_extension_invocation_extension_code on extension_invocation(extension_code);
create index ix_extension_invocation_created_at on extension_invocation(created_at);
create index ix_ext_invocation_trace on extension_invocation(trace_id);

create table extension_routing_rule (
    id varchar(64) primary key,
    rule_name varchar(255) not null,
    extension_code varchar(128) not null,
    source_version varchar(64),
    target_version varchar(64) not null,
    tenant_id varchar(64),
    user_id varchar(128),
    scene varchar(128),
    priority int not null default 0,
    traffic_percent int not null default 0,
    enabled boolean not null default true,
    created_at timestamp not null default now(),
    created_by varchar(128),
    updated_at timestamp,
    unique(extension_code, source_version, target_version, tenant_id, user_id, scene)
);

create index ix_ext_routing_extension_code on extension_routing_rule(extension_code);
create index ix_ext_routing_tenant on extension_routing_rule(tenant_id);
create index ix_ext_routing_enabled on extension_routing_rule(enabled);
create index ix_ext_routing_priority on extension_routing_rule(priority);

create table extension_resource_limit (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    tenant_id varchar(64),
    limit_type varchar(64) not null,
    max_value bigint not null,
    current_value bigint not null default 0,
    window_seconds int not null default 60,
    created_at timestamp not null default now(),
    updated_at timestamp,
    unique(extension_code, tenant_id, limit_type)
);

create index ix_ext_res_limit_code on extension_resource_limit(extension_code);
create index ix_ext_res_limit_tenant on extension_resource_limit(tenant_id);

create table extension_rollback_point (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    version varchar(64) not null,
    artifact_uri text,
    config_snapshot text,
    routing_rule_ids text,
    created_at timestamp not null default now(),
    created_by varchar(128),
    is_active boolean not null default true
);

create index ix_ext_rollback_code on extension_rollback_point(extension_code);
create index ix_ext_rollback_active on extension_rollback_point(is_active);

create table extension_audit_event (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_version varchar(64),
    event_type varchar(64) not null,
    actor varchar(128) not null,
    tenant_id varchar(64),
    user_id varchar(128),
    trace_id varchar(128),
    trust_level varchar(32),
    details text,
    severity varchar(32) not null default 'INFO',
    created_at timestamp not null default now()
);

create index ix_ext_audit_code on extension_audit_event(extension_code);
create index ix_ext_audit_type on extension_audit_event(event_type);
create index ix_ext_audit_tenant on extension_audit_event(tenant_id);
create index ix_ext_audit_trace on extension_audit_event(trace_id);
create index ix_ext_audit_created on extension_audit_event(created_at);

create table sandbox_execution_job (
    id varchar(64) primary key,
    extension_code varchar(128),
    language varchar(32) not null,
    script_hash varchar(64),
    status varchar(32) not null default 'PENDING',
    trace_id varchar(128),
    tenant_id varchar(64),
    user_id varchar(128),
    timeout_ms bigint not null default 30000,
    started_at timestamp,
    finished_at timestamp,
    exit_code int,
    output_preview text,
    error_message text,
    created_at timestamp not null default now()
);

create index ix_sandbox_job_status on sandbox_execution_job(status);
create index ix_sandbox_job_trace on sandbox_execution_job(trace_id);
create index ix_sandbox_job_extension on sandbox_execution_job(extension_code);

create table problematic_data_record (
    record_id varchar(64) primary key,
    data_type varchar(64) not null,
    data_id varchar(128) not null,
    tenant_id varchar(64),
    user_id varchar(128),
    problematic_type varchar(64) not null,
    severity varchar(32) not null default 'MEDIUM',
    detection_rule varchar(64),
    description text,
    context_json text,
    source_session_id varchar(128),
    render_job_id varchar(128),
    prompt_execution_id varchar(128),
    provider_key varchar(64),
    worker_id varchar(64),
    status varchar(32) not null default 'DETECTED',
    auto_fix_applied text,
    quarantine_table varchar(128),
    requires_human_review boolean not null default false,
    human_review_notes text,
    detected_at timestamp not null default now(),
    resolved_at timestamp,
    resolved_by varchar(128)
);

create index idx_problematic_data_tenant on problematic_data_record(tenant_id);
create index idx_problematic_data_status on problematic_data_record(status);
create index idx_problematic_data_type on problematic_data_record(problematic_type);
create index idx_problematic_data_severity on problematic_data_record(severity);
create index idx_problematic_data_render_job on problematic_data_record(render_job_id);
create index idx_problematic_data_prompt_exec on problematic_data_record(prompt_execution_id);
create index idx_problematic_data_detected_at on problematic_data_record(detected_at);
create index idx_problematic_data_human_review on problematic_data_record(requires_human_review, status);

create table quarantined_render_jobs (
    quarantine_id varchar(64) primary key,
    original_job_id varchar(128) not null,
    tenant_id varchar(64),
    quarantine_reason varchar(64) not null,
    detection_rule varchar(64),
    original_data_json text,
    status varchar(32) not null default 'QUARANTINED',
    quarantined_at timestamp not null default now(),
    resolved_at timestamp,
    resolved_by varchar(128),
    resolution_notes text
);

create table quarantined_prompt_executions (
    quarantine_id varchar(64) primary key,
    original_execution_id varchar(128) not null,
    tenant_id varchar(64),
    quarantine_reason varchar(64) not null,
    detection_rule varchar(64),
    original_data_json text,
    status varchar(32) not null default 'QUARANTINED',
    quarantined_at timestamp not null default now(),
    resolved_at timestamp,
    resolved_by varchar(128),
    resolution_notes text
);

create table quarantined_provider_workers (
    quarantine_id varchar(64) primary key,
    provider_key varchar(64),
    worker_id varchar(64),
    tenant_id varchar(64),
    quarantine_reason varchar(64) not null,
    detection_rule varchar(64),
    original_data_json text,
    status varchar(32) not null default 'QUARANTINED',
    quarantined_at timestamp not null default now(),
    resolved_at timestamp,
    resolved_by varchar(128),
    resolution_notes text
);

create table problematic_data_rule_config (
    rule_id varchar(64) primary key,
    rule_name varchar(255) not null,
    data_type varchar(64) not null,
    default_severity varchar(32) not null default 'MEDIUM',
    description text,
    detection_query text,
    auto_fixable boolean not null default false,
    auto_fix_action varchar(255),
    enabled boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('RJB-001', 'Missing RenderJob Output', 'MISSING_FIELD', 'HIGH', 'RenderJob completed but has no output artifact', false, '', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('RJB-002', 'Stuck RenderJob', 'INVALID_STATE_TRANSITION', 'MEDIUM', 'RenderJob stuck in non-terminal state for too long', true, 'MARK_STALE_AND_RETRY', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('RJB-003', 'Duplicate RenderJob', 'DUPLICATE_ENTRY', 'LOW', 'Multiple render jobs with same project+profile+timeline hash', true, 'MARK_DUPLICATE', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('PMT-001', 'Prompt Sensitive Data Leak', 'MISSING_FIELD', 'CRITICAL', 'Sensitive prompt variable found in execution record', false, '', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('PMT-002', 'Prompt Output Mismatch', 'OUTPUT_MISMATCH', 'HIGH', 'Prompt execution output does not match expected format', false, '', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('PRV-001', 'Provider Error Spike', 'ERROR_RATE_SPIKE', 'HIGH', 'Provider error rate exceeds threshold in time window', false, '', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('WRK-001', 'Worker Stale Heartbeat', 'PERFORMANCE_ANOMALY', 'MEDIUM', 'Remote worker has not sent heartbeat within expected interval', true, 'MARK_WORKER_OFFLINE', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('SLA-001', 'SLA Breach', 'SLA_BREACH', 'CRITICAL', 'Render job exceeded SLA time limit', false, '', true);
insert into problematic_data_rule_config (rule_id, rule_name, data_type, default_severity, description, auto_fixable, auto_fix_action, enabled)
values ('CST-001', 'Cost Anomaly', 'COST_ANOMALY', 'HIGH', 'Render job cost significantly exceeds estimated cost', false, '', true);

create table nlq_report_definition (
    report_id varchar(64) not null primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    name varchar(255) not null,
    description text,
    widgets_json text,
    query_definitions_json text,
    created_by varchar(128),
    visibility varchar(32) not null default 'PRIVATE',
    schedule_json text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    archived boolean not null default false
);

create index ix_nlq_report_tenant on nlq_report_definition(tenant_id);
create index ix_nlq_report_workspace on nlq_report_definition(workspace_id);

create table nlq_query_history (
    query_id varchar(64) not null primary key,
    user_id varchar(128) not null,
    tenant_id varchar(64),
    workspace_id varchar(64),
    question_redacted text,
    sql_hash varchar(64),
    datasets_json text,
    row_count int not null default 0,
    duration_ms bigint not null default 0,
    risk_level varchar(32),
    status varchar(32) not null,
    error_code varchar(64),
    created_at timestamp not null default now()
);

create index ix_nlq_history_tenant on nlq_query_history(tenant_id);
create index ix_nlq_history_user on nlq_query_history(user_id);

create table nlq_report_execution (
    execution_id varchar(64) not null primary key,
    report_id varchar(64) not null,
    status varchar(32) not null,
    row_count int not null default 0,
    duration_ms bigint not null default 0,
    error_code varchar(64),
    created_at timestamp not null default now()
);

create index ix_nlq_report_exec_report on nlq_report_execution(report_id);


-- ============================================================
-- 7. GOVERNANCE & COMPLIANCE
-- ============================================================
-- feature_flag_definition, feature_flag_targeting_rule,
-- frontend_route_definition, navigation_policy,
-- notification_event_definition, notification_channel_binding,
-- notification_subscription, notification_preference,
-- notification_delivery_record, notification_user_inbox

create table feature_flag_definition (
    id varchar(64) primary key,
    flag_key varchar(128) not null unique,
    name varchar(255) not null,
    description text,
    flag_type varchar(32) not null default 'BOOLEAN',
    enabled boolean not null default false,
    default_value_json text,
    variants_json text,
    tags_json text,
    owner varchar(128),
    archived boolean not null default false,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create table feature_flag_targeting_rule (
    id varchar(64) primary key,
    flag_key varchar(128) not null,
    rule_id varchar(64),
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64),
    role varchar(64),
    tier varchar(64),
    percentage double precision,
    priority int not null default 0,
    enabled boolean not null default true,
    rule_json text not null,
    created_at timestamp not null default now()
);

create index ix_feature_flag_targeting_flag on feature_flag_targeting_rule(flag_key);

create table frontend_route_definition (
    id varchar(64) not null primary key,
    route_key varchar(128) not null unique,
    path varchar(256) not null,
    component_key varchar(128) not null,
    title varchar(256) not null,
    description text,
    menu_group varchar(128),
    icon varchar(64),
    sort_order int not null default 0,
    parent_route_key varchar(128),
    required_permissions text,
    required_roles text,
    required_entitlements text,
    required_tier varchar(64),
    required_features text,
    supported_sources text,
    visible boolean not null default true,
    enabled boolean not null default true,
    hidden_reason varchar(512),
    disabled_reason varchar(512),
    upgrade_options text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index ix_route_def_menu_group on frontend_route_definition(menu_group);
create index ix_route_def_visible on frontend_route_definition(visible);
create index ix_route_def_enabled on frontend_route_definition(enabled);
create index ix_route_def_parent on frontend_route_definition(parent_route_key);

create table navigation_policy (
    id varchar(64) not null primary key,
    policy_key varchar(128) not null unique,
    route_key varchar(128) not null,
    policy_type varchar(32) not null,
    condition_expr text not null,
    effect varchar(16) not null,
    reason_code varchar(128) not null,
    reason_message text not null,
    upgrade_options text,
    priority int not null default 0,
    enabled boolean not null default true,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    constraint fk_nav_policy_route foreign key (route_key)
        references frontend_route_definition(route_key)
        on delete cascade
);

create index ix_nav_policy_route on navigation_policy(route_key);
create index ix_nav_policy_priority on navigation_policy(priority);

create table notification_event_definition (
    id varchar(64) primary key,
    event_key varchar(100) not null unique,
    name varchar(200) not null,
    description varchar(500),
    category varchar(50) not null,
    severity varchar(20) not null,
    visibility varchar(30) not null,
    user_configurable boolean not null default false,
    critical boolean not null default false,
    default_enabled boolean not null default true,
    supported_channels text,
    required_permissions text,
    required_entitlements text,
    feature_flag_key varchar(100),
    novu_workflow_id varchar(100),
    local_template_key varchar(100),
    archived boolean not null default false,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table notification_channel_binding (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64) not null,
    channel_type varchar(32) not null,
    destination_masked varchar(255),
    destination_encrypted text,
    verified boolean not null default false,
    verification_status varchar(32) not null default 'PENDING',
    enabled boolean not null default true,
    failure_count int not null default 0,
    last_failure_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_notification_channel_binding_user on notification_channel_binding(user_id);

create table notification_subscription (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64) not null,
    event_key varchar(100) not null,
    enabled boolean not null default true,
    channels text,
    frequency varchar(30) not null default 'IMMEDIATE',
    filters text,
    quiet_hours_start varchar(10),
    quiet_hours_end varchar(10),
    quiet_hours_timezone varchar(50),
    created_at timestamp not null,
    updated_at timestamp not null
);

create index ix_notification_subscription_user on notification_subscription(user_id);

create table notification_preference (
    id varchar(64) primary key,
    tenant_id varchar(64),
    user_id varchar(64) not null,
    event_key varchar(100) not null,
    enabled boolean not null default true,
    channels text,
    created_at timestamp not null,
    updated_at timestamp not null,
    unique(tenant_id, user_id, event_key)
);

create table notification_delivery_record (
    id varchar(64) primary key,
    event_key varchar(100) not null,
    tenant_id varchar(64),
    user_id varchar(64),
    channel_type varchar(32) not null,
    status varchar(32) not null,
    attempts int not null default 0,
    payload_redacted text,
    provider_message_id varchar(128),
    error_code varchar(64),
    sent_at timestamp,
    failed_at timestamp,
    created_at timestamp not null
);

create index ix_notification_delivery_record_user on notification_delivery_record(user_id);

create table notification_user_inbox (
    id varchar(64) primary key,
    tenant_id varchar(64),
    workspace_id varchar(64),
    user_id varchar(64) not null,
    event_key varchar(100),
    type varchar(32) not null default 'INFO',
    title varchar(255),
    message text,
    read boolean not null default false,
    link varchar(512),
    actor_id varchar(64),
    resource_type varchar(64),
    resource_id varchar(64),
    created_at timestamp not null,
    read_at timestamp
);

create index ix_notification_user_inbox_user on notification_user_inbox(user_id);


-- ============================================================
-- 8. DELIVERY & PUBLISHING
-- ============================================================
-- delivery_destination, delivery_policy, delivery_job,
-- social_connected_platform, social_post, social_post_analytics

create table delivery_destination (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    user_id varchar(64),
    name varchar(255) not null,
    protocol varchar(32) not null,
    config_json text,
    credential_json text,
    enabled boolean default true,
    verified_at timestamp,
    created_at timestamp not null,
    credential_ref varchar(512)
);

create index ix_delivery_destination_tenant on delivery_destination(tenant_id);
create index ix_delivery_destination_credential_ref on delivery_destination(credential_ref);

create table delivery_policy (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    project_id varchar(64),
    destination_id varchar(64) not null,
    artifact_selector varchar(32) not null default 'FINAL_ONLY',
    path_template varchar(512) not null,
    trigger_mode varchar(16) not null default 'AUTO',
    enabled boolean default true,
    created_at timestamp not null
);

create index ix_delivery_policy_tenant_project on delivery_policy(tenant_id, project_id);

create table delivery_job (
    id varchar(64) primary key,
    tenant_id varchar(64) not null,
    project_id varchar(64) not null,
    render_job_id varchar(64) not null,
    destination_id varchar(64) not null,
    status varchar(32) not null,
    source_uri varchar(1024) not null,
    remote_path varchar(1024),
    remote_uri varchar(1024),
    bytes_transferred bigint,
    attempt_count int not null default 0,
    error_code varchar(64),
    error_message varchar(2048),
    created_at timestamp not null,
    completed_at timestamp
);

create index ix_delivery_job_render on delivery_job(render_job_id);
create index ix_delivery_job_status on delivery_job(status);

create table social_connected_platform (
    id varchar(36) primary key,
    tenant_id varchar(36) not null,
    user_id varchar(36) not null,
    platform_type varchar(32) not null,
    platform_user_id varchar(256),
    platform_username varchar(256),
    access_token_encrypted text,
    refresh_token_encrypted text,
    token_expires_at timestamp,
    status varchar(16) default 'ACTIVE',
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index ix_social_connected_platform_tenant_user on social_connected_platform(tenant_id, user_id);

create table social_post (
    id varchar(36) primary key,
    tenant_id varchar(36) not null,
    user_id varchar(36) not null,
    content_text text,
    media_urls varchar(4000),
    platform_type varchar(32) not null,
    status varchar(16) default 'DRAFT',
    platform_post_id varchar(256),
    platform_post_url varchar(512),
    scheduled_at timestamp,
    published_at timestamp,
    failed_at timestamp,
    error_code varchar(64),
    error_message text,
    retry_count int default 0,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create index ix_social_post_tenant_user on social_post(tenant_id, user_id);
create index ix_social_post_status on social_post(status);

create table social_post_analytics (
    id varchar(36) primary key,
    post_id varchar(36) not null,
    platform_type varchar(32) not null,
    impressions int default 0,
    reach int default 0,
    likes int default 0,
    comments int default 0,
    shares int default 0,
    clicks int default 0,
    fetched_at timestamp,
    created_at timestamp not null default now()
);

create index ix_social_post_analytics_post on social_post_analytics(post_id);


-- ============================================================
-- 9. ANALYTICS & USER
-- ============================================================
-- user_behavior_event, user_profile, user_segment, user_habits,
-- shared_resource_grant

create table user_behavior_event (
    event_id varchar(64) not null primary key,
    tenant_id varchar(64) not null,
    user_id varchar(128) not null,
    event_type varchar(64) not null,
    action varchar(128),
    resource_type varchar(64),
    resource_id varchar(128),
    metadata_json text,
    occurred_at timestamp not null default now()
);

create index ix_user_behavior_tenant on user_behavior_event(tenant_id);
create index ix_user_behavior_user on user_behavior_event(user_id);
create index ix_user_behavior_occurred on user_behavior_event(occurred_at);

create table user_profile (
    profile_id varchar(64) not null primary key,
    tenant_id varchar(64) not null,
    user_id varchar(128) not null,
    display_name varchar(255),
    preferred_languages_json text,
    feature_usage_counts_json text,
    action_counts_json text,
    total_sessions int not null default 0,
    total_actions int not null default 0,
    first_seen_at timestamp,
    last_active_at timestamp,
    updated_at timestamp not null default now(),
    unique(tenant_id, user_id)
);

create index ix_user_profile_tenant on user_profile(tenant_id);

create table user_segment (
    segment_id varchar(64) not null primary key,
    tenant_id varchar(64) not null,
    name varchar(255) not null,
    description text,
    criteria_json text,
    user_ids_json text,
    user_count int not null default 0,
    computed_at timestamp not null default now()
);

create index ix_user_segment_tenant on user_segment(tenant_id);

create table user_habits (
    tenant_id varchar(64) not null,
    user_id varchar(128) not null,
    habits_json text not null,
    computed_at timestamp not null default now(),
    primary key (tenant_id, user_id)
);

create table shared_resource_grant (
    grant_id varchar(64) not null primary key,
    tenant_id varchar(64) not null,
    resource_type varchar(32) not null,
    resource_id varchar(128) not null,
    resource_name varchar(255),
    resource_description text,
    resource_status varchar(32),
    shared_by_user_id varchar(128),
    shared_with_user_id varchar(128) not null,
    permission varchar(32) not null default 'READ',
    status varchar(32) not null default 'ACTIVE',
    created_at timestamp not null default now(),
    expires_at timestamp
);

create index ix_shared_resource_grant_recipient on shared_resource_grant(tenant_id, shared_with_user_id);
create index ix_shared_resource_grant_resource on shared_resource_grant(resource_type, resource_id);


-- ============================================================
-- 10. AI & LITELLM
-- ============================================================
-- tenant_litellm_virtual_key

create table tenant_litellm_virtual_key (
    tenant_id varchar(64) primary key,
    virtual_key varchar(512),
    key_alias varchar(128),
    enabled boolean not null default true,
    created_at timestamp not null,
    updated_at timestamp not null,
    vault_ref varchar(512)
);

create index ix_tenant_litellm_key_enabled on tenant_litellm_virtual_key(enabled);
create index ix_tenant_litellm_vault_ref on tenant_litellm_virtual_key(vault_ref);
