create table if not exists render_job (
    id varchar(64) primary key,
    project_id varchar(128) not null,
    timeline_snapshot_id varchar(128) not null,
    profile varchar(128) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists notification_event (
    id varchar(64) primary key,
    event_type varchar(128) not null,
    subject_id varchar(128),
    payload text not null,
    created_at timestamp not null
);

create table if not exists notification_template (
    id bigint generated by default as identity primary key,
    template_code varchar(64) not null,
    channel varchar(32) not null,
    locale varchar(16) not null,
    version int not null,
    subject_template varchar(255),
    body_template text not null,
    unique(template_code, channel, locale, version)
);

create table if not exists notification_delivery (
    id varchar(64) primary key,
    event_id varchar(64) not null,
    channel varchar(32) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    request_payload text,
    response_payload text,
    attempt_count int not null,
    created_at timestamp not null
);

create table if not exists config_item (
    id bigint generated by default as identity primary key,
    namespace_key varchar(128) not null,
    config_key varchar(128) not null,
    value_json text not null,
    value_version int not null,
    updated_at timestamp not null,
    unique(namespace_key, config_key, value_version)
);