-- Merged schema (greenfield): core infrastructure


create table if not exists render_job (
    id varchar(64) primary key,
    project_id varchar(128) not null,
    timeline_snapshot_id varchar(128) not null,
    profile varchar(128) not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists notification_event (
    id varchar(64) primary key,
    event_type varchar(128) not null,
    subject_id varchar(128),
    payload text not null,
    created_at timestamp not null
);

create table if not exists notification_template (
    id bigint generated by default as identity primary key,
    template_code varchar(64) not null,
    channel varchar(32) not null,
    locale varchar(16) not null,
    version int not null,
    subject_template varchar(255),
    body_template text not null,
    unique(template_code, channel, locale, version)
);

create table if not exists notification_delivery (
    id varchar(64) primary key,
    event_id varchar(64) not null,
    channel varchar(32) not null,
    provider_code varchar(64) not null,
    status varchar(32) not null,
    request_payload text,
    response_payload text,
    attempt_count int not null,
    created_at timestamp not null
);

create table if not exists config_item (
    id bigint generated by default as identity primary key,
    namespace_key varchar(128) not null,
    config_key varchar(128) not null,
    value_json text not null,
    value_version int not null,
    updated_at timestamp not null,
    unique(namespace_key, config_key, value_version)
);

create table if not exists storage_object (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    bucket varchar(128) not null,
    object_key text not null,
    content_type varchar(255),
    checksum_sha256 varchar(128),
    file_size_bytes bigint,
    lifecycle_policy varchar(64),
    created_at timestamp not null
);

create table if not exists cloud_resource_definition (
    id varchar(64) primary key,
    provider_code varchar(64) not null,
    resource_type varchar(64) not null,
    logical_name varchar(128) not null,
    spec_json text not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create table if not exists secret_ref (
    id varchar(64) primary key,
    namespace_key varchar(128) not null,
    secret_key varchar(128) not null,
    backend_type varchar(64) not null,
    backend_ref varchar(255) not null,
    created_at timestamp not null,
    unique(namespace_key, secret_key)
);

create table if not exists extension_definition (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_type varchar(64) not null,
    language varchar(32),
    runtime varchar(64),
    version varchar(64) not null,
    artifact_uri text,
    status varchar(32) not null,
    timeout_ms bigint,
    config_schema text,
    created_at timestamp not null,
    unique(extension_code, version)
);

create table if not exists extension_invocation (
    id varchar(64) primary key,
    extension_code varchar(128) not null,
    extension_version varchar(64) not null,
    caller_module varchar(128) not null,
    input_summary text,
    output_summary text,
    exit_status varchar(32),
    duration_ms bigint,
    created_at timestamp not null
);

create table if not exists app_datasource (
    id varchar(64) primary key,
    datasource_code varchar(64) not null unique,
    datasource_kind varchar(32) not null,
    dialect varchar(32),
    jdbc_url text,
    secret_ref varchar(255),
    is_primary boolean not null,
    usage_role varchar(64) not null,
    created_at timestamp not null
);

create table if not exists outbox_events (
  id varchar(64) primary key,
  aggregate_type varchar(100) not null,
  aggregate_id varchar(100) not null,
  event_type varchar(150) not null,
  event_version int not null,
  payload text not null,
  status varchar(50) not null,
  created_at timestamp not null,
  published_at timestamp
);

create table if not exists audit_records (
  id varchar(64) primary key,
  actor_type varchar(50) not null,
  actor_id varchar(100),
  action varchar(120) not null,
  resource_type varchar(120) not null,
  resource_id varchar(120),
  payload text,
  created_at timestamp not null
);

create table if not exists schedules (
  id varchar(64) primary key,
  schedule_code varchar(100) not null,
  handler_code varchar(120) not null,
  enabled boolean not null,
  created_at timestamp not null
);

create table if not exists quota_definitions (
  id varchar(64) primary key,
  quota_code varchar(80) not null,
  unit varchar(50) not null,
  created_at timestamp not null
);


-- Enhance outbox_events with retry tracking, dead-letter support, and idempotency
-- Note: H2-compatible syntax (no IF EXISTS on ALTER TABLE)
alter table outbox_events add column if not exists retry_count int not null default 0;
alter table outbox_events add column if not exists next_attempt_at timestamp;
alter table outbox_events add column if not exists idempotency_key varchar(255);

-- Enhance audit_records with category support
alter table audit_records add column if not exists category varchar(50);
