package com.example.platform.studio.camera;
import com.example.platform.shared.digest.ContentDigest;import com.example.platform.studio.digest.StudioDigest;import com.example.platform.studio.directorintent.DirectorIntentVersion;import com.example.platform.studio.identity.*;import com.example.platform.studio.reference.StudioVersionPin;import com.example.platform.studio.scope.StudioScope;import com.example.platform.studio.serialization.CanonicalJson;import com.example.platform.studio.shot.ShotVersion;import com.example.platform.studio.shotplan.ShotPlanVersion;import java.util.*;
public final class CameraPlanVersion implements com.example.platform.studio.digest.CanonicalStudioVersion{
public static final int SCHEMA_VERSION=1;public enum Projection{PERSPECTIVE,ORTHOGRAPHIC}public enum Framing{EXTREME_WIDE,WIDE,MEDIUM,CLOSE_UP,EXTREME_CLOSE_UP}public enum TargetIntent{SUBJECT,RELATIONSHIP,ENVIRONMENT,DETAIL}
private final CameraPlanId id;private final CameraPlanVersionId versionId;private final StudioScope scope;private final CameraPlanVersionId parentVersionId;private final Projection projection;private final Framing framing;private final TargetIntent targetIntent;private final CameraPose pose;private final CameraOptics optics;private final StudioVersionPin<ShotId,ShotVersionId>shotPin;private final StudioVersionPin<ShotPlanId,ShotPlanVersionId>shotPlanPin;private final StudioVersionPin<DirectorIntentId,DirectorIntentVersionId>directorIntentPin;private final List<CameraKeyframe>keyframes;private final byte[]canonicalBytes;private final ContentDigest semanticDigest;
private CameraPlanVersion(CameraPlanId id,CameraPlanVersionId versionId,StudioScope scope,CameraPlanVersionId parentVersionId,Projection projection,Framing framing,TargetIntent targetIntent,CameraPose pose,CameraOptics optics,ShotVersion shot,ShotPlanVersion plan,DirectorIntentVersion intent,List<CameraKeyframe>keyframes){if(id==null||versionId==null||scope==null||projection==null||framing==null||targetIntent==null||pose==null||optics==null||shot==null||plan==null||intent==null||keyframes==null)throw new IllegalArgumentException("camera plan fields are required");if(versionId.equals(parentVersionId))throw new IllegalArgumentException("version cannot parent itself");if(!scope.equals(shot.scope())||!scope.equals(plan.scope())||!scope.equals(intent.scope()))throw new IllegalArgumentException("camera pin scope mismatch");if(!plan.shotPins().contains(shot.pin()))throw new IllegalArgumentException("shot is not in exact shot plan");for(int i=1;i<keyframes.size();i++)if(keyframes.get(i-1).time().compareTo(keyframes.get(i).time())>=0)throw new IllegalArgumentException("keyframe times must be strictly increasing");this.id=id;this.versionId=versionId;this.scope=scope;this.parentVersionId=parentVersionId;this.projection=projection;this.framing=framing;this.targetIntent=targetIntent;this.pose=pose;this.optics=optics;this.shotPin=shot.pin();this.shotPlanPin=plan.pin();this.directorIntentPin=intent.pin();this.keyframes=List.copyOf(keyframes);this.canonicalBytes=serialize();this.semanticDigest=StudioDigest.sha256(canonicalBytes);}
public static CameraPlanVersion create(CameraPlanId id,CameraPlanVersionId versionId,StudioScope scope,CameraPlanVersionId parentVersionId,Projection projection,Framing framing,TargetIntent targetIntent,CameraPose pose,CameraOptics optics,ShotVersion shot,ShotPlanVersion plan,DirectorIntentVersion intent,List<CameraKeyframe>keyframes){return new CameraPlanVersion(id,versionId,scope,parentVersionId,projection,framing,targetIntent,pose,optics,shot,plan,intent,keyframes);}
private byte[]serialize(){Map<String,String>m=new LinkedHashMap<>();m.put("aggregateId",CanonicalJson.quote(id.value()));m.put("directorIntentPin",directorIntentPin.canonicalJson());m.put("framing",CanonicalJson.quote(framing.name()));m.put("keyframes",CanonicalJson.array(keyframes.stream().map(CameraKeyframe::canonicalJson).toList()));m.put("optics",optics.canonicalJson());if(parentVersionId!=null)m.put("parentVersionId",CanonicalJson.quote(parentVersionId.value()));m.put("pose",pose.canonicalJson());m.put("projectId",CanonicalJson.quote(scope.projectId().value()));m.put("projection",CanonicalJson.quote(projection.name()));m.put("schemaVersion","1");m.put("shotPin",shotPin.canonicalJson());m.put("shotPlanPin",shotPlanPin.canonicalJson());m.put("targetIntent",CanonicalJson.quote(targetIntent.name()));m.put("tenantId",CanonicalJson.quote(scope.tenantId().value()));m.put("type",CanonicalJson.quote("CAMERA_PLAN_VERSION"));m.put("versionId",CanonicalJson.quote(versionId.value()));return CanonicalJson.utf8(CanonicalJson.object(m));}
public StudioVersionPin<CameraPlanId,CameraPlanVersionId>pin(){return new StudioVersionPin<>(StudioVersionPin.AggregateKind.CAMERA_PLAN,id,versionId,scope,1,semanticDigest);}public CameraPlanId id(){return id;}public CameraPlanVersionId versionId(){return versionId;}public StudioScope scope(){return scope;}public CameraPlanVersionId parentVersionId(){return parentVersionId;}public byte[]canonicalBytes(){return canonicalBytes.clone();}public ContentDigest semanticDigest(){return semanticDigest;}public CameraPose pose(){return pose;}public List<CameraKeyframe>keyframes(){return keyframes;}
}
