package com.example.platform.render.domain.timeline.render.plan;

/**
 * Issue codes for FFmpeg/libass basic render planning.
 * Immutable enum. Internal domain model.
 */
public enum FFmpegLibassBasicRenderPlanIssueCode {
    INVALID_REQUEST,
    INVALID_TIMELINE,
    TIMELINE_VALIDATION_FAILED,
    MISSING_OUTPUT_PROFILE,
    INVALID_OUTPUT_PROFILE,
    MISSING_CLIP,
    INVALID_CLIP_SEQUENCE,
    EFFECT_PLAN_FAILED,
    EFFECT_PLAN_BLOCKED,
    EFFECT_PLAN_UNSUPPORTED,
    TRANSITION_PLAN_FAILED,
    TRANSITION_PLAN_BLOCKED,
    TRANSITION_PLAN_UNSUPPORTED,
    CAPTION_OVERLAY_INVALID,
    WATERMARK_OVERLAY_INVALID,
    UNSUPPORTED_OUTPUT_CONTAINER,
    UNSUPPORTED_VIDEO_CODEC,
    UNSUPPORTED_AUDIO_CODEC,
    RAW_FILTERGRAPH_FORBIDDEN,
    RAW_PROVIDER_COMMAND_FORBIDDEN,
    USER_RENDER_DAG_FORBIDDEN,
    PLUGIN_EXECUTION_NODE_FORBIDDEN,
    REMOTION_EXECUTION_FORBIDDEN,
    ARTIFACT_DAG_NOT_USED,
    OPEN_CUE_NOT_USED,
    RENDER_EXECUTION_NOT_ALLOWED,
    PRODUCT_CREATION_NOT_ALLOWED,
    STORAGE_RUNTIME_FORBIDDEN,
    PRODUCT_RUNTIME_FORBIDDEN,
    PROVIDER_INTERNALS_FORBIDDEN,
    PERSISTENCE_NOT_IMPLEMENTED,
    PUBLIC_API_NOT_IMPLEMENTED
}
