package com.example.platform.render.domain.timeline.editing;

/**
 * Issue codes for timeline validation.
 * Immutable enum. Internal domain model.
 */
public enum TimelineValidationIssueCode {
    INVALID_TIMELINE_ID,
    INVALID_OUTPUT_PROFILE,
    DUPLICATE_TRACK_ID,
    TRACK_NOT_FOUND,
    DUPLICATE_CLIP_ID,
    CLIP_NOT_FOUND,
    INVALID_CLIP_TIME_RANGE,
    DUPLICATE_CAPTION_ID,
    INVALID_CAPTION_TIME_RANGE,
    DUPLICATE_WATERMARK_ID,
    INVALID_WATERMARK_PLACEMENT,
    EFFECT_TARGET_NOT_FOUND,
    EFFECT_CAPABILITY_NOT_FOUND,
    EFFECT_CAPABILITY_FORBIDDEN,
    EFFECT_CAPABILITY_RESTRICTED,
    TRANSITION_CLIP_NOT_FOUND,
    TRANSITION_CAPABILITY_NOT_FOUND,
    TRANSITION_CAPABILITY_FORBIDDEN,
    INVALID_TRANSITION_DURATION,
    RAW_PROVIDER_COMMAND_FORBIDDEN,
    ARBITRARY_FILTERGRAPH_FORBIDDEN,
    USER_RENDER_DAG_FORBIDDEN,
    PLUGIN_EXECUTION_NODE_FORBIDDEN,
    STORAGE_INTERNALS_FORBIDDEN,
    PROVIDER_INTERNALS_FORBIDDEN,
    ARTIFACT_DAG_NOT_USED,
    RENDER_NOT_ALLOWED,
    PRODUCT_CREATION_NOT_ALLOWED,
    PERSISTENCE_NOT_IMPLEMENTED
}
