package com.example.platform.storage.contract.provider;
public enum ProviderCapability {
    RANGE_READ, STREAMING_READ, STREAMING_WRITE, MULTIPART_WRITE,
    CONDITIONAL_CREATE, CONDITIONAL_WRITE, NATIVE_CHECKSUM,
    COPY, RENAME, DELETE, BATCH_DELETE,
    PRESIGN_READ, PRESIGN_WRITE, VERSIONING, OBJECT_METADATA, LIST
}
