package com.example.platform.notification.testsupport;

import org.jooq.DSLContext;

/**
 * Shared PostgreSQL test schema fixture for notification-module tests.
 *
 * <p>Uses actual production table definitions from V1__init_full_schema.sql.
 * All SQL is PostgreSQL-compatible.
 */
public final class NotificationTestSchemaFixture {

    private NotificationTestSchemaFixture() {}

    /**
     * Create all notification tables if they don't exist.
     */
    public static void createSchema(DSLContext dsl) {
        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_event (
                id varchar(64) primary key,
                event_type varchar(128) not null,
                subject_id varchar(128),
                payload text not null,
                created_at timestamp not null
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_event_definition (
                id varchar(64) primary key,
                event_key varchar(100) not null unique,
                name varchar(200) not null,
                description varchar(500),
                category varchar(50) not null,
                severity varchar(20) not null,
                visibility varchar(30) not null,
                user_configurable boolean not null default false,
                critical boolean not null default false,
                default_enabled boolean not null default true,
                supported_channels text,
                required_permissions text,
                required_entitlements text,
                feature_flag_key varchar(100),
                novu_workflow_id varchar(100),
                local_template_key varchar(100),
                archived boolean not null default false,
                created_at timestamp not null,
                updated_at timestamp not null
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_template (
                id bigint generated by default as identity primary key,
                template_code varchar(64) not null,
                channel varchar(32) not null,
                locale varchar(16) not null,
                version int not null,
                subject_template varchar(255),
                body_template text not null,
                unique(template_code, channel, locale, version)
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_subscription (
                id varchar(64) primary key,
                tenant_id varchar(64),
                workspace_id varchar(64),
                user_id varchar(64) not null,
                event_key varchar(100) not null,
                enabled boolean not null default true,
                channels text,
                frequency varchar(30) not null default 'IMMEDIATE',
                filters text,
                quiet_hours_start varchar(10),
                quiet_hours_end varchar(10),
                quiet_hours_timezone varchar(50),
                created_at timestamp not null,
                updated_at timestamp not null
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_channel_binding (
                id varchar(64) primary key,
                tenant_id varchar(64),
                workspace_id varchar(64),
                user_id varchar(64) not null,
                channel_type varchar(32) not null,
                destination_masked varchar(255),
                destination_encrypted text,
                verified boolean not null default false,
                verification_status varchar(32) not null default 'PENDING',
                enabled boolean not null default true,
                provider varchar(50),
                failure_count int not null default 0,
                last_failure_at timestamp,
                disabled_reason varchar(200),
                created_at timestamp not null,
                updated_at timestamp not null,
                last_verified_at timestamp
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_record (
                id varchar(64) primary key,
                event_id varchar(64) not null,
                channel varchar(32) not null,
                provider_code varchar(64) not null,
                status varchar(32) not null,
                subject varchar(512),
                body text,
                metadata_json text,
                attempt_count int not null default 1,
                created_at timestamp not null
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_delivery (
                id varchar(64) primary key,
                event_id varchar(64) not null,
                channel varchar(32) not null,
                provider_code varchar(64) not null,
                status varchar(32) not null,
                request_payload text,
                response_payload text,
                attempt_count int not null,
                created_at timestamp not null
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_preference (
                id varchar(64) primary key,
                tenant_id varchar(64),
                user_id varchar(64) not null,
                event_key varchar(100) not null,
                enabled boolean not null default true,
                channels text,
                created_at timestamp not null,
                updated_at timestamp not null,
                unique(tenant_id, user_id, event_key)
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_delivery_record (
                id varchar(64) primary key,
                event_key varchar(100) not null,
                tenant_id varchar(64),
                user_id varchar(64),
                channel_type varchar(32) not null,
                status varchar(32) not null,
                attempts int not null default 0,
                payload_redacted text,
                provider_message_id varchar(128),
                error_code varchar(64),
                sent_at timestamp,
                failed_at timestamp,
                created_at timestamp not null
            )
        """);

        dsl.execute("""
            CREATE TABLE IF NOT EXISTS notification_user_inbox (
                id varchar(64) primary key,
                tenant_id varchar(64),
                workspace_id varchar(64),
                user_id varchar(64) not null,
                event_key varchar(100),
                type varchar(32) not null default 'INFO',
                title varchar(255),
                message text,
                read boolean not null default false,
                link varchar(512),
                actor_id varchar(64),
                resource_type varchar(64),
                resource_id varchar(64),
                created_at timestamp not null,
                read_at timestamp
            )
        """);
    }

    /**
     * Truncate all notification tables.
     */
    public static void truncate(DSLContext dsl) {
        dsl.execute("""
            TRUNCATE TABLE
                notification_user_inbox,
                notification_delivery_record,
                notification_preference,
                notification_delivery,
                notification_record,
                notification_channel_binding,
                notification_subscription,
                notification_template,
                notification_event_definition,
                notification_event
            RESTART IDENTITY CASCADE
        """);
    }
}
