import { vi } from 'vitest'
import type { Revision, ReviewDetail, TimelineReviewSource } from './api'
export const revision: Revision = { id: 'r1', revisionNumber: 1, parentRevisionId: null, snapshotId: 's1', internalRevision: 1, source: 'EDITOR', message: 'Opening cut', labels: ['first'], authorUserId: 'reader', editSessionId: null, patchOpCount: 2, createdAt: '2026-09-13T00:00:00Z', changeSummary: { supported: true, tracksAdded: 1, tracksRemoved: 0, tracksModified: 0, clipsAdded: 2, clipsRemoved: 0, clipsModified: 0, assetsAdded: 1, assetsRemoved: 0, parentInternalRevision: 0, currentInternalRevision: 1 }, isMerge: false, mergeParentRevisionIds: null, mergeBaseRevisionId: null }
export const review = { reviewId: 'review1', projectId: 'p', revisionId: 'r1', authorUserId: 'reader', title: 'Opening review', description: 'Check the opening', status: 'OPEN', createdAt: null, updatedAt: null }
export const detail: ReviewDetail = { review, comments: [{ commentId: 'c', reviewId: 'review1', threadId: 't', revisionId: 'r1', entityRef: 'CLIP:clip1', authorUserId: 'reader', content: 'Long comment '+ 'x'.repeat(3000), createdAt: null }], threads: [{ threadId: 't', reviewId: 'review1', entityRef: 'CLIP:clip1', diffId: null, status: 'OPEN', createdAt: null }], decisions: [{ decisionId: 'd', reviewId: 'review1', reviewerUserId: 'reader', decision: 'REQUEST_CHANGES', createdAt: null }], mergeGuard: { canMerge: false, reason: 'Review is OPEN — approval required' } }
export const project = { id: 'p', tenantId: 'tenant', name: 'Film', description: null, status: 'ACTIVE', createdAt: null }
export function source(): TimelineReviewSource {
  return { projects: vi.fn().mockResolvedValue([project, { ...project, id: 'empty', name: 'Empty film' }]), project: vi.fn().mockImplementation(async (_tenant, id) => ({ ...project, id })), revisions: vi.fn().mockImplementation(async id => id === 'empty' ? [] : [revision]), head: vi.fn().mockImplementation(async id => id === 'empty' ? null : revision), reviews: vi.fn().mockImplementation(async id => id === 'empty' ? [] : [review]), detail: vi.fn().mockResolvedValue(detail) }
}
export function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(done => { resolve = done }); return { promise, resolve } }
