package com.example.platform.timeline.patch;

/**
 * Error codes for patch application failures.
 */
public enum PatchErrorCode {
    TIMELINE_PATCH_REVISION_NOT_FOUND,
    TIMELINE_PATCH_CROSS_PRODUCT_NOT_ALLOWED,
    TIMELINE_PATCH_BASE_NOT_CURRENT,
    TIMELINE_PATCH_BASE_DIGEST_MISMATCH,
    TIMELINE_PATCH_SCHEMA_INCOMPATIBLE,
    TIMELINE_PATCH_PAYLOAD_INVALID,
    TIMELINE_PATCH_CONFLICTING_OPERATIONS,
    TIMELINE_PATCH_PRECONDITION_FAILED,
    TIMELINE_PATCH_TARGET_NOT_FOUND,
    TIMELINE_PATCH_TARGET_ALREADY_EXISTS,
    TIMELINE_PATCH_POSITION_INVALID,
    TIMELINE_PATCH_RESULT_DIGEST_MISMATCH,
    TIMELINE_PATCH_REVISION_CONFLICT,
    TIMELINE_PATCH_NO_CHANGES
}
