import { useEffect, useState } from 'react'
import { cancelThumbnail, getThumbnail, listThumbnailAssets, submitThumbnail, type ThumbnailAsset, type ThumbnailTask } from '../../api/thumbnail'
import { useParams } from '@tanstack/react-router'
import { useWorkspaceHome } from '../../foundation/platformClient'

export function ThumbnailWorkspace() {
  const {workspaceId,projectId}=useParams({strict:false}) as {workspaceId:string;projectId:string}; const baseUrl=''
  const home=useWorkspaceHome(workspaceId)
  const [assets,setAssets]=useState<ThumbnailAsset[]>([]); const [asset,setAsset]=useState(''); const [time,setTime]=useState('0'); const [task,setTask]=useState<ThumbnailTask|null>(null); const [error,setError]=useState(''); const [loadingAssets,setLoadingAssets]=useState(false)
  const tenantId=home.data?.tenantId ?? ''
  useEffect(()=>{ if(!projectId||home.unavailable)return; const controller=new AbortController(); setLoadingAssets(true); void listThumbnailAssets({baseUrl},projectId,controller.signal).then(r=>{if(r.success)setAssets(r.data.filter(a=>/^video\//.test(a.mediaType)||/^audio\//.test(a.mediaType)))}).catch(()=>setError('Source media could not be loaded.')).finally(()=>setLoadingAssets(false)); return()=>controller.abort()},[projectId,home.unavailable])
  useEffect(()=>{ if(!task||!['ADMITTED','RUNNING','COMMITTING'].includes(task.status)||!tenantId)return; const timer=window.setInterval(async()=>{const r=await getThumbnail({baseUrl},tenantId,projectId,task.taskId);if(r.success)setTask(r.data)},1000);return()=>window.clearInterval(timer)},[task,tenantId,projectId])
  async function request(){if(!tenantId||!asset)return;setError('');const r=await submitThumbnail({baseUrl},tenantId,projectId,{sourceAssetId:asset,timestampSeconds:Number(time),imageFormat:'jpeg',idempotencyKey:`ui-${projectId}-${asset}-${time}`});if(r.success)setTask(r.data);else setError(r.error.message)}
  async function cancel(){if(!tenantId||!task)return;const r=await cancelThumbnail({baseUrl},tenantId,projectId,task.taskId);if(r.success)setTask(r.data);else setError(r.error.message)}
  if(home.unavailable||!tenantId)return <main aria-label="Media thumbnail"><p role="alert">Workspace session is unavailable or expired.</p></main>
  return <main aria-label="Media thumbnail"><h1>Media thumbnail</h1><label>Source media<select aria-label="Source media" value={asset} onChange={e=>setAsset(e.target.value)} disabled={loadingAssets}><option value="">{loadingAssets?'Loading authorized media…':'Choose source media'}</option>{assets.map(a=><option key={a.id} value={a.id}>{a.filename||a.id}</option>)}</select></label><label>Timestamp (seconds)<input type="number" min="0" step="0.01" value={time} onChange={e=>setTime(e.target.value)} /></label><button disabled={!asset||!time||Boolean(task&&['ADMITTED','RUNNING','COMMITTING'].includes(task.status))} onClick={request}>Request thumbnail</button>{task&&['ADMITTED','RUNNING','COMMITTING'].includes(task.status)&&<button onClick={cancel}>Cancel</button>}{error&&<p role="alert">{error}</p>}{task&&<section aria-live="polite"><p>Status: {task.status}</p>{task.failureCode&&<p role="alert">Failed: {task.failureCode}</p>}{task.status==='COMPLETED'&&<><img src={`${baseUrl}/api/tenants/${encodeURIComponent(tenantId)}/projects/${encodeURIComponent(projectId)}/thumbnails/${task.taskId}/image`} alt="Committed thumbnail" /><a href={`${baseUrl}/api/tenants/${encodeURIComponent(tenantId)}/projects/${encodeURIComponent(projectId)}/thumbnails/${task.taskId}/image`}>Open/download image</a></>}</section>}</main>
}
