package com.example.platform.render.domain.timeline.render.effect;

/**
 * Issue codes for FFmpeg baseline effect planning.
 * Immutable enum. Internal domain model.
 */
public enum FFmpegBaselineEffectPlanIssueCode {
    INVALID_REQUEST,
    INVALID_TIMELINE,
    EFFECT_NOT_FOUND,
    EFFECT_TARGET_NOT_FOUND,
    EFFECT_CAPABILITY_NOT_FOUND,
    EFFECT_CAPABILITY_UNSUPPORTED,
    EFFECT_CAPABILITY_FORBIDDEN,
    EFFECT_CAPABILITY_RESTRICTED,
    EFFECT_CAPABILITY_POC_ONLY,
    INVALID_EFFECT_PARAMETER,
    MISSING_REQUIRED_PARAMETER,
    UNSUPPORTED_PARAMETER,
    INVALID_OPERATION_TARGET,
    RAW_FILTERGRAPH_FORBIDDEN,
    RAW_PROVIDER_COMMAND_FORBIDDEN,
    USER_RENDER_DAG_FORBIDDEN,
    PLUGIN_EXECUTION_NODE_FORBIDDEN,
    REMOTION_EXECUTION_FORBIDDEN,
    ARTIFACT_DAG_NOT_USED,
    RENDER_NOT_ALLOWED,
    PRODUCT_CREATION_NOT_ALLOWED,
    STORAGE_INTERNALS_FORBIDDEN,
    PROVIDER_INTERNALS_FORBIDDEN,
    PERSISTENCE_NOT_IMPLEMENTED
}
